/* @autogenerated */
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { DeviceInstanceViewListPageComponent } from './device-instance-view-list-page.component';
import { DeviceInstanceViewListModule } from '@features/installations/device-instance/components/device-instance-view-list/device-instance-view-list.module';

const routes: Routes = [{ path: '', component: DeviceInstanceViewListPageComponent }];
@NgModule({
  declarations: [DeviceInstanceViewListPageComponent],
  imports: [RouterModule.forChild(routes), DeviceInstanceViewListModule],
  exports: [RouterModule],
})
export class DeviceInstanceViewListRouteModule {}
