/* @autogenerated */
import { ActionContainerComponent } from 'app/common/toolkit/action/action-container.component';
import { ConfigTemplateViewCreateActionModule } from 'app/features/infrastructure/config-template/actions/config-template-view-create-action/config-template-view-create-action.module';
import { ConfigTemplateViewEditActionModule } from 'app/features/infrastructure/config-template/actions/config-template-view-edit-action/config-template-view-edit-action.module';
import { ConfigTemplateViewDetailActionModule } from 'app/features/infrastructure/config-template/actions/config-template-view-detail-action/config-template-view-detail-action.module';
import { ConfigTemplateViewDeleteActionModule } from 'app/features/infrastructure/config-template/actions/config-template-view-delete-action/config-template-view-delete-action.module';
import { ConfigTemplateViewDeleteSelectionActionModule } from 'app/features/infrastructure/config-template/actions/config-template-view-delete-selection-action/config-template-view-delete-selection-action.module';
import { ConfigTemplateViewStandarActionsComponent } from './config-template-view-standar-actions.component';
import { provideTranslocoScope } from '@jsverse/transloco';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [ConfigTemplateViewStandarActionsComponent],
  exports: [ConfigTemplateViewStandarActionsComponent],
  imports: [
    ActionContainerComponent,
    ConfigTemplateViewCreateActionModule,
    ConfigTemplateViewDeleteActionModule,
    ConfigTemplateViewDeleteSelectionActionModule,
    ConfigTemplateViewDetailActionModule,
    ConfigTemplateViewEditActionModule,
  ],
  providers: [
    provideTranslocoScope({ scope: 'infrastructure/config-template', alias: 'infrastructure.config-template' }),
  ],
  bootstrap: [],
})
export class ConfigTemplateViewStandarActionsModule {}
