/* @autogenerated */
import { EditableTextComponent } from 'app/common/toolkit/editable/editable-text/editable-text.component';
import { EditableSelectoneComponent } from 'app/common/toolkit/editable/editable-selectone/editable-selectone.component';
import { EditableDecimalComponent } from 'app/common/toolkit/editable/editable-decimal/editable-decimal.component';
import { MatInputModule } from '@angular/material/input';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { FormLayoutComponent } from 'app/common/toolkit/form-layout/form-layout.component';
import { ProjectDeviceViewFormGroupComponent } from './project-device-view-form-group.component';
import { provideTranslocoScope } from '@jsverse/transloco';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [ProjectDeviceViewFormGroupComponent],
  exports: [ProjectDeviceViewFormGroupComponent],
  imports: [
    CommonModule,
    EditableDecimalComponent,
    EditableSelectoneComponent,
    EditableTextComponent,
    FormLayoutComponent,
    FormsModule,
    MatInputModule,
    ReactiveFormsModule,
  ],
  providers: [provideTranslocoScope({ scope: 'installations/project-device', alias: 'installations.project-device' })],
  bootstrap: [],
})
export class ProjectDeviceViewFormGroupModule {}
