/* @autogenerated */
import { InjectionToken } from '@angular/core';
import { Observable } from 'rxjs';

export const IDENTITY_PROVIDER = new InjectionToken<IdentityProvider>('IdentityProvider');

export interface IdentityProvider {
  accept(type: string, name: string): IdentityHandler | null;
}

export interface IdentityHandler {
  bootstrap(): Observable<void>;
  login(): void;
  logout(): void;
}
