/* @autogenerated */
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { ProjectViewListPageComponent } from './project-view-list-page.component';
import { ProjectViewListModule } from '@features/installations/project/components/project-view-list/project-view-list.module';

const routes: Routes = [{ path: '', component: ProjectViewListPageComponent }];
@NgModule({
  declarations: [ProjectViewListPageComponent],
  imports: [RouterModule.forChild(routes), ProjectViewListModule],
  exports: [RouterModule],
})
export class ProjectViewListRouteModule {}
