/* @autogenerated */
import { DeviceInstance } from '../model/device-instance.model';
import { Observable, of } from 'rxjs';
export function appwriteReader(data: any): DeviceInstance {
  const copy = { ...data } as any;
  copy.projectDevice = { $ref: data.projectDevice, $id: (data as any).projectDevice?.$id };
  copy.model = { $ref: data.model, $id: (data as any).model?.$id };
  return copy;
}
