/* @autogenerated */
import { DeviceInstance } from '../model/device-instance.model';
import { Observable, of } from 'rxjs';
export function appwriteDataNormalizer(data: DeviceInstance): Observable<DeviceInstance> {
  const copy = { ...data } as any;
  copy.projectDevice = (data as any)?.projectDevice?.$ref;
  copy.model = (data as any)?.model?.$ref;
  return of(copy);
}
