/* @autogenerated */
import { DeviceInstanceFilter } from '../model/device-instance.model';
import { Observable, of } from 'rxjs';
export function appwriteQuery(query: DeviceInstanceFilter): Observable<string[]> {
  const constraints: string[] = [];
  return of(constraints);
}
