/* @autogenerated */
import { appwriteQuery } from './appwrite-query.method';
import { DisplayProvider } from '@common/data/display-provider';
import { appwriteAcl } from './appwrite-acl.method';
import {
  DeviceInstanceProjection,
  DeviceInstance,
  DeviceInstanceFilter,
} from '@features/installations/device-instance/model/device-instance.model';
import { selectorProvider, SelectorProvider } from '@common/data/selector-provider';
import { RepositoryService, RepositoryMetadata } from '@common/data/repository/repository.service';
import { Acl } from '@common/data/acl/acl.model';
import { appwriteReader } from './appwrite-reader.method';
import { appwriteDataNormalizer } from './appwrite-data-normalizer.method';
import { Slide, DownloadBlob, UploadProgress } from '@common/data/repository/provider/repository-provider.interface';
import { AppwriteDataBuilder } from '@common/appwrite/data/appwrite-data-builder.service';
import { ModelRepository } from '@features/infrastructure/model/repository/model-repository.service';
import { of, Observable } from 'rxjs';
import { Signal, Injectable } from '@angular/core';
import { ProjectDeviceRepository } from '@features/installations/project-device/repository/project-device-repository.service';
import { Tick, Shift } from '@common/data/repository/repository.model';

@Injectable({ providedIn: 'root' })
export class DeviceInstanceRepository {
  private readonly repo: RepositoryService<DeviceInstance, DeviceInstanceFilter>;
  public static metadata(api: AppwriteDataBuilder): RepositoryMetadata<DeviceInstance, DeviceInstanceFilter> {
    return {
      key: 'uid',
      name: 'device-instance',
      provider: api.provider(
        'uid',
        'netconfighub_documents',
        'netconfighub_device_instance',
        'netconfighub_attacheds',
        appwriteAcl,
        appwriteQuery,
        appwriteReader,
        appwriteDataNormalizer,
      ),
      reference: (name: string): RepositoryService<any, any> | null => {
        if ('projectDevice' == name) {
          return new RepositoryService(ProjectDeviceRepository.metadata(api));
        }
        if ('model' == name) {
          return new RepositoryService(ModelRepository.metadata(api));
        }
        return null;
      },
    };
  }
  constructor(api: AppwriteDataBuilder) {
    this.repo = new RepositoryService(DeviceInstanceRepository.metadata(api));
  }
  acl(): Tick<{ generic: Acl; specific: Acl }, string | null> {
    return this.repo.acl();
  }
  checkAcl(key?: string): Observable<Acl> {
    return this.repo.checkAcl(key || null);
  }
  generateComb(): string {
    return this.repo.generateComb();
  }

  add(item: DeviceInstance): Observable<DeviceInstance> {
    item['uid'] = this.generateComb();
    return this.repo.add(item);
  }
  update(item: DeviceInstance): Observable<DeviceInstance> {
    return this.repo.update(item);
  }
  deleteByKey(item: string): Observable<void> {
    return this.repo.deleteByKey(item);
  }
  canDeleteSelection(): boolean {
    return this.repo.canDeleteSelection();
  }
  deleteSelection(filter: DeviceInstanceFilter): Observable<any> {
    return this.repo.deleteSelection(this.publicQueryFilter(filter));
  }
  retrieve(code: string): Observable<DeviceInstance | undefined> {
    return this.repo.retrieve(code);
  }
  projection(includes: string[]): Tick<DeviceInstanceProjection, string> {
    return this.repo.projection(includes);
  }
  list(filter: DeviceInstanceFilter): Observable<Slide<DeviceInstance>> {
    return this.repo.list(this.publicQueryFilter(filter));
  }
  values(filter: DeviceInstanceFilter): Observable<DeviceInstance[]> {
    return this.repo.values(this.publicQueryFilter(filter));
  }
  projections(includes: string[]): Shift<DeviceInstanceProjection[], DeviceInstanceFilter> {
    return this.repo.projections(includes);
  }
  downloadModelPhoto(url?: string): Observable<DownloadBlob> | null {
    return url ? this.repo.downloadFile(url) : null;
  }
  storeModelPhoto(file: File): Observable<UploadProgress> {
    return this.repo.storeFile('/-/temp-model-photo', 'file', file);
  }
  downloadSerialNumberPhoto(url?: string): Observable<DownloadBlob> | null {
    return url ? this.repo.downloadFile(url) : null;
  }
  storeSerialNumberPhoto(file: File): Observable<UploadProgress> {
    return this.repo.storeFile('/-/temp-serial-number-photo', 'file', file);
  }
  downloadPlacementPhoto(url?: string): Observable<DownloadBlob> | null {
    return url ? this.repo.downloadFile(url) : null;
  }
  storePlacementPhoto(file: File): Observable<UploadProgress> {
    return this.repo.storeFile('/-/temp-placement-photo', 'file', file);
  }
  displayProvider(): DisplayProvider<DeviceInstance> {
    return {
      display: (item: DeviceInstance) => {
        return item.serialNumber!;
      },
    };
  }
  selectorProvider(filter?: Signal<DeviceInstanceFilter>): SelectorProvider<DeviceInstance, { $ref: string }> {
    return selectorProvider({
      search: (text: string) => {
        const filterValue = filter ? filter() : { limit: 10 };
        filterValue.search = text;
        return this.values(filterValue);
      },
      display: (item: DeviceInstance) => {
        return item.serialNumber!;
      },
      value: (item: DeviceInstance) => {
        return { $ref: item.uid!, $id: (item as any).$id };
      },
      select: (ref: { $ref: string }) => {
        return ref['$ref'] ? this.retrieve(ref['$ref']) : of(undefined);
      },
      equals: (one: { $ref: string }, other: { $ref: string }) => {
        return one.$ref === other.$ref;
      },
    });
  }
  private publicQueryFilter(filter: DeviceInstanceFilter): DeviceInstanceFilter {
    const morphed = {} as any;
    if (filter.search) {
      morphed['search'] = filter.search;
    }
    if (filter.uids) {
      morphed['uids'] = filter.uids.join(',');
    }
    if (filter.limit) {
      morphed['limit'] = filter.limit;
    }
    if (filter.order) {
      morphed['order'] = filter.order;
    }
    if (filter.serialNumber) {
      morphed['serial-number'] = filter.serialNumber;
    }
    if (filter.projectDevice) {
      morphed['project-device'] = filter.projectDevice;
    }
    if (filter.projectDevices) {
      morphed['project-devices'] = filter.projectDevices;
    }
    if (filter.model) {
      morphed['model'] = filter.model;
    }
    if (filter.models) {
      morphed['models'] = filter.models;
    }
    return morphed;
  }
}
