/* @autogenerated */
import { QueryConstraint, where } from 'firebase/firestore';
import { DeviceInstanceFilter } from '../model/device-instance.model';
import { Observable, of } from 'rxjs';
export function firebaseQuery(query: DeviceInstanceFilter): Observable<QueryConstraint[]> {
  const constraints: QueryConstraint[] = [];
  return of(constraints);
}
