/* @autogenerated */
import { QueryConstraint, where } from 'firebase/firestore';
import { DeviceInstance } from '../model/device-instance.model';
import { Observable, of } from 'rxjs';
export function firebaseDataNormalizer(data: DeviceInstance): Observable<DeviceInstance> {
  return of(data);
}
