/* @autogenerated */
import { SelectorProvider } from 'app/common/data/selector-provider';
import { DeviceCheck } from 'app/features/installations/device-check/model/device-check.model';
import { DeviceCheckRepository } from 'app/features/installations/device-check/repository/device-check-repository.service';
import { Tick } from 'app/common/data/repository/repository.model';
import { Acl } from 'app/common/data/acl/acl.model';
import { ProjectDeviceRepository } from 'app/features/installations/project-device/repository/project-device-repository.service';
import { SubFormEditable } from 'app/common/toolkit/editable/subform-editable';
import {
  ProjectDevice,
  ProjectDeviceFilter,
} from 'app/features/installations/project-device/model/project-device.model';
import { BaseEditable } from 'app/common/toolkit/editable/base-editable';
import { Validators, FormGroup, FormControl } from '@angular/forms';
import { effect, computed, Component, input } from '@angular/core';

@Component({
  selector: 'device-check-view-form-group',
  templateUrl: './device-check-view-form-group.component.html',
  styleUrls: ['./device-check-view-form-group.component.scss'],
  providers: BaseEditable.getValidableAccessorProvider(DeviceCheckViewFormGroupComponent),
  standalone: false,
})
export class DeviceCheckViewFormGroupComponent extends SubFormEditable<DeviceCheck> {
  acl: Tick<{ generic: Acl; specific: Acl }, string | null>;
  uid = computed(() => this.value()?.uid);
  projectDeviceProvider: SelectorProvider<ProjectDevice, { $ref: string }>;
  projectDeviceFilter = input<ProjectDeviceFilter>({ limit: 100 });
  public constructor(deviceCheckRepository: DeviceCheckRepository, projectDeviceRepository: ProjectDeviceRepository) {
    super(
      new FormGroup({
        uid: new FormControl<string>(''),
        projectDevice: new FormControl<any>(null, [Validators.required]),
        result: new FormControl<any>('pass', [Validators.required]),
        details: new FormControl<string>(''),
        checkedAt: new FormControl<Date>(new Date(), [Validators.required]),
        checkedBy: new FormControl<string>('', [Validators.required]),
        version: new FormControl<number>(0),
      }),
    );
    this.acl = deviceCheckRepository.acl();
    effect(() => {
      this.acl.fetch(this.uid() || null);
    });
    effect(() => {
      const vals = this.acl();
      const value = this.value();
      const on = this.uid() ? vals?.specific : vals?.generic;
      setTimeout(() => {
        this.definedFixed.set(on?.fields?.noEditables || []);
        this.definedHidden.set(on?.fields?.noVisibles || []);
      });
    });
    this.projectDeviceProvider = projectDeviceRepository.selectorProvider(this.projectDeviceFilter);
    this.defaultValues = () => {
      return {
        uid: '',
        projectDevice: null,
        result: 'pass',
        details: '',
        checkedAt: new Date(),
        checkedBy: '',
        version: 0,
      };
    };
  }
}
