/* @autogenerated */
import { ActionContainerComponent } from 'app/common/toolkit/action/action-container.component';
import { DeviceCheckViewCreateActionModule } from 'app/features/installations/device-check/actions/device-check-view-create-action/device-check-view-create-action.module';
import { DeviceCheckViewEditActionModule } from 'app/features/installations/device-check/actions/device-check-view-edit-action/device-check-view-edit-action.module';
import { DeviceCheckViewDetailActionModule } from 'app/features/installations/device-check/actions/device-check-view-detail-action/device-check-view-detail-action.module';
import { DeviceCheckViewDeleteActionModule } from 'app/features/installations/device-check/actions/device-check-view-delete-action/device-check-view-delete-action.module';
import { DeviceCheckViewDeleteSelectionActionModule } from 'app/features/installations/device-check/actions/device-check-view-delete-selection-action/device-check-view-delete-selection-action.module';
import { DeviceCheckViewStandarActionsComponent } from './device-check-view-standar-actions.component';
import { provideTranslocoScope } from '@jsverse/transloco';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [DeviceCheckViewStandarActionsComponent],
  exports: [DeviceCheckViewStandarActionsComponent],
  imports: [
    ActionContainerComponent,
    DeviceCheckViewCreateActionModule,
    DeviceCheckViewDeleteActionModule,
    DeviceCheckViewDeleteSelectionActionModule,
    DeviceCheckViewDetailActionModule,
    DeviceCheckViewEditActionModule,
  ],
  providers: [provideTranslocoScope({ scope: 'installations/device-check', alias: 'installations.device-check' })],
  bootstrap: [],
})
export class DeviceCheckViewStandarActionsModule {}
