/* @autogenerated */
import { TranslocoModule, provideTranslocoScope } from '@jsverse/transloco';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { SiteViewFormGroupModule } from 'app/features/organization/site/components/site-view-form-group/site-view-form-group.module';
import { SiteViewCreateActionComponent } from './site-view-create-action.component';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [SiteViewCreateActionComponent],
  exports: [SiteViewCreateActionComponent],
  imports: [CommonModule, MatButtonModule, ReactiveFormsModule, SiteViewFormGroupModule, TranslocoModule],
  providers: [provideTranslocoScope({ scope: 'organization/site', alias: 'organization.site' })],
  bootstrap: [],
})
export class SiteViewCreateActionModule {}
