/* @autogenerated */
import { TranslocoModule, provideTranslocoScope } from '@jsverse/transloco';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { ProjectViewFormGroupModule } from 'app/features/installations/project/components/project-view-form-group/project-view-form-group.module';
import { ProjectViewEditActionComponent } from './project-view-edit-action.component';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [ProjectViewEditActionComponent],
  exports: [ProjectViewEditActionComponent],
  imports: [CommonModule, MatButtonModule, ProjectViewFormGroupModule, ReactiveFormsModule, TranslocoModule],
  providers: [provideTranslocoScope({ scope: 'installations/project', alias: 'installations.project' })],
  bootstrap: [],
})
export class ProjectViewEditActionModule {}
