/* @autogenerated */
import { Component, input, OnDestroy, output, Signal } from '@angular/core';
import { toSignal } from '@angular/core/rxjs-interop';
import { AppConfigService } from '@common/context/config/app-config.service';
import { IdentityService } from '@common/context/identity/identity.service';
import { AppStateService } from '@common/context/state/app-state.service';
import { MatButtonModule } from '@angular/material/button';
import { MatMenuModule } from '@angular/material/menu';
import { MatIconModule } from '@angular/material/icon';
import { CommonModule } from '@angular/common';
import { Subscription } from 'rxjs';
import { MatToolbarModule } from '@angular/material/toolbar';
import { UserInfo } from '@common/context/identity/user-info.model';

@Component({
  selector: 'app-toolbar',
  standalone: true,
  imports: [CommonModule, MatButtonModule, MatIconModule, MatToolbarModule, MatMenuModule],
  templateUrl: './toolbar.component.html',
  styleUrl: './toolbar.component.scss',
})
export class ToolbarComponent implements OnDestroy {
  menuClicked = output<void>();
  user = input<UserInfo | null>();

  title: Signal<string | undefined>;
  currentLanguage: Signal<string | undefined>;
  currentTenant: Signal<string | undefined>;

  private subscriptions = new Subscription();

  public constructor(
    private readonly identity: IdentityService,
    appstate: AppStateService,
    appconfig: AppConfigService,
  ) {
    this.title = toSignal(appconfig['meta.title']);
    this.currentLanguage = toSignal(appstate.language);
    this.currentTenant = toSignal(appstate.tenant);
  }

  ngOnDestroy(): void {
    this.subscriptions.unsubscribe();
  }

  toogleMenu(): void {
    this.menuClicked.emit();
  }

  login(): void {
    this.identity.login('main');
  }

  logout(): void {
    this.identity.logout('main');
  }
}
