/* @autogenerated */
import { Project } from 'app/features/installations/project/model/project.model';
import { FormControl } from '@angular/forms';
import { input, effect, Component } from '@angular/core';

@Component({
  selector: 'project-view-detail',
  templateUrl: './project-view-detail.component.html',
  styleUrl: './project-view-detail.component.scss',
  standalone: false,
})
export class ProjectViewDetailComponent {
  data = input.required<Project | null>();
  form = new FormControl<Project | undefined>({ value: undefined, disabled: true });

  public constructor() {
    effect(() => this.form.patchValue(this.data()));
  }
}
