/* @autogenerated */
import { ProjectDevice } from 'app/features/installations/project-device/model/project-device.model';
import { FormControl } from '@angular/forms';
import { input, effect, Component } from '@angular/core';

@Component({
  selector: 'project-device-view-detail',
  templateUrl: './project-device-view-detail.component.html',
  styleUrl: './project-device-view-detail.component.scss',
  standalone: false,
})
export class ProjectDeviceViewDetailComponent {
  data = input.required<ProjectDevice | null>();
  form = new FormControl<ProjectDevice | undefined>({ value: undefined, disabled: true });

  public constructor() {
    effect(() => this.form.patchValue(this.data()));
  }
}
