/* @autogenerated */
import { Model } from '../model/model.model';
import { Observable, of } from 'rxjs';
export function appwriteDataNormalizer(data: Model): Observable<Model> {
  const copy = { ...data } as any;
  copy.vendor = (data as any)?.vendor?.$ref;
  copy.type = (data as any)?.type?.$ref;
  return of(copy);
}
