/* @autogenerated */
import { Acl } from '@common/data/acl/acl.model';
import { Observable, of } from 'rxjs';
export function firebaseAcl(): Observable<Acl> {
  return of({
    allows: [
      { name: 'create', allowed: true },
      { name: 'update', allowed: true },
      { name: 'delete', allowed: true },
      { name: 'list', allowed: true },
      { name: 'retrieve', allowed: true },
    ],
  });
}
