/* @autogenerated */
import { QueryConstraint, where } from 'firebase/firestore';
import { Model } from '../model/model.model';
import { Observable, of } from 'rxjs';
export function firebaseDataNormalizer(data: Model): Observable<Model> {
  return of(data);
}
