/* @autogenerated */
import { QueryConstraint, where } from 'firebase/firestore';
import { ModelFilter } from '../model/model.model';
import { Observable, of } from 'rxjs';
export function firebaseQuery(query: ModelFilter): Observable<QueryConstraint[]> {
  const constraints: QueryConstraint[] = [];
  return of(constraints);
}
