/* @autogenerated */
import { ActionContainerComponent } from 'app/common/toolkit/action/action-container.component';
import { DeviceInstanceViewCreateActionModule } from 'app/features/installations/device-instance/actions/device-instance-view-create-action/device-instance-view-create-action.module';
import { DeviceInstanceViewEditActionModule } from 'app/features/installations/device-instance/actions/device-instance-view-edit-action/device-instance-view-edit-action.module';
import { DeviceInstanceViewDetailActionModule } from 'app/features/installations/device-instance/actions/device-instance-view-detail-action/device-instance-view-detail-action.module';
import { DeviceInstanceViewDeleteActionModule } from 'app/features/installations/device-instance/actions/device-instance-view-delete-action/device-instance-view-delete-action.module';
import { DeviceInstanceViewDeleteSelectionActionModule } from 'app/features/installations/device-instance/actions/device-instance-view-delete-selection-action/device-instance-view-delete-selection-action.module';
import { DeviceInstanceViewStandarActionsComponent } from './device-instance-view-standar-actions.component';
import { provideTranslocoScope } from '@jsverse/transloco';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [DeviceInstanceViewStandarActionsComponent],
  exports: [DeviceInstanceViewStandarActionsComponent],
  imports: [
    ActionContainerComponent,
    DeviceInstanceViewCreateActionModule,
    DeviceInstanceViewDeleteActionModule,
    DeviceInstanceViewDeleteSelectionActionModule,
    DeviceInstanceViewDetailActionModule,
    DeviceInstanceViewEditActionModule,
  ],
  providers: [
    provideTranslocoScope({ scope: 'installations/device-instance', alias: 'installations.device-instance' }),
  ],
  bootstrap: [],
})
export class DeviceInstanceViewStandarActionsModule {}
