/* @autogenerated */
import { TranslocoModule, provideTranslocoScope } from '@jsverse/transloco';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { DeviceInstanceViewDetailModule } from 'app/features/installations/device-instance/components/device-instance-view-detail/device-instance-view-detail.module';
import { DeviceInstanceViewDetailActionComponent } from './device-instance-view-detail-action.component';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [DeviceInstanceViewDetailActionComponent],
  exports: [DeviceInstanceViewDetailActionComponent],
  imports: [CommonModule, DeviceInstanceViewDetailModule, MatButtonModule, ReactiveFormsModule, TranslocoModule],
  providers: [
    provideTranslocoScope({ scope: 'installations/device-instance', alias: 'installations.device-instance' }),
  ],
  bootstrap: [],
})
export class DeviceInstanceViewDetailActionModule {}
