/* @autogenerated */
import { ModelViewStandarActionsModule } from 'app/features/infrastructure/model/components/model-view-standar-actions/model-view-standar-actions.module';
import { ModelViewListComponent } from './model-view-list.component';
import { CommonModule } from '@angular/common';
import { ListViewModule } from '@common/toolkit/list-view/list-view.module';
import { TranslocoModule, provideTranslocoScope } from '@jsverse/transloco';
import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';
import { MatExpansionModule } from '@angular/material/expansion';
import { ReactiveFormsModule } from '@angular/forms';
import { ModelViewSearchModule } from '../model-view-search/model-view-search.module';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [ModelViewListComponent],
  exports: [ModelViewListComponent],
  imports: [
    CommonModule,
    ListViewModule,
    MatButtonModule,
    MatExpansionModule,
    MatIconModule,
    ModelViewSearchModule,
    ModelViewStandarActionsModule,
    ReactiveFormsModule,
    TranslocoModule,
  ],
  providers: [provideTranslocoScope({ scope: 'infrastructure/model', alias: 'infrastructure.model' })],
  bootstrap: [],
})
export class ModelViewListModule {}
