# @autogenerated
# Etapa 1: Construcción de la aplicación Angular
FROM node:18 AS build

# Establecer el directorio de trabajo en la etapa de construcción
WORKDIR /app

# Copiar el package.json y el package-lock.json
COPY package*.json ./

# Instalar las dependencias de Node.js
RUN npm install

# Copiar el resto del código del proyecto
COPY . .

# Construir la aplicación Angular
RUN npm run build --prod

# Etapa 2: Servir la aplicación con Nginx
FROM nginx:alpine

# Eliminar el archivo de configuración por defecto de Nginx
RUN rm /etc/nginx/conf.d/default.conf
RUN rm /usr/share/nginx/html/index.html

RUN cat <<'EOF' > /etc/nginx/conf.d/default.conf
server {
    listen 80;

    server_name localhost;

    root /usr/share/nginx/html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    error_page 404 /index.html;
}
EOF
# COPY docker/nginx.conf  /etc/nginx/conf.d/default.conf

# Copiar los archivos compilados de Angular desde la etapa de construcción
COPY --from=build /app/dist/netconfighub/browser /usr/share/nginx/html

# Exponer el puerto 80
EXPOSE 80

# Comando para iniciar Nginx
CMD ["nginx", "-g", "daemon off;"]
