/* @autogenerated */
import { Component, Host, input, Optional, output, SkipSelf } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { SpeedDialComponent } from './speed-dial.component';

@Component({
  selector: 'speed-dial-button',
  imports: [MatButtonModule, MatIconModule],
  template: `
    <button matMiniFab [color]="color()" (click)="onClick($event)" style="margin: 3px;">
      <mat-icon>{{ icon() }}</mat-icon>
    </button>
  `,
})
export class SpeedDialButtonComponent {
  click = output<void>();
  icon = input<string>('add');
  color = input<string>('accent');

  constructor(@Optional() @Host() @SkipSelf() private parent: SpeedDialComponent | null) {}

  onClick(event: Event) {
    event.preventDefault();
    event.stopPropagation();
    this.click.emit();
    this.parent?.toggleFab();
  }
}
