/* @autogenerated */
import { SelectorProvider } from 'app/common/data/selector-provider';
import { SiteRepository } from 'app/features/organization/site/repository/site-repository.service';
import { Tick } from 'app/common/data/repository/repository.model';
import { Acl } from 'app/common/data/acl/acl.model';
import { ProjectRepository } from 'app/features/installations/project/repository/project-repository.service';
import { SubFormEditable } from 'app/common/toolkit/editable/subform-editable';
import { Project } from 'app/features/installations/project/model/project.model';
import { BaseEditable } from 'app/common/toolkit/editable/base-editable';
import { FormGroup, FormControl } from '@angular/forms';
import { Site, SiteFilter } from 'app/features/organization/site/model/site.model';
import { effect, computed, Component, input } from '@angular/core';

@Component({
  selector: 'project-view-search',
  templateUrl: './project-view-search.component.html',
  styleUrls: ['./project-view-search.component.scss'],
  providers: BaseEditable.getValidableAccessorProvider(ProjectViewSearchComponent),
  standalone: false,
})
export class ProjectViewSearchComponent extends SubFormEditable<any> {
  acl: Tick<{ generic: Acl; specific: Acl }, string | null>;
  uid = computed(() => this.value()?.uid);
  siteProvider: SelectorProvider<Site, { $ref: string }>;
  siteFilter = input<SiteFilter>({ limit: 100 });
  sitesProvider: SelectorProvider<Site, { $ref: string }>;
  sitesFilter = input<SiteFilter>({ limit: 100 });
  public constructor(projectRepository: ProjectRepository, siteRepository: SiteRepository) {
    super(
      new FormGroup({
        search: new FormControl<string>(''),
        site: new FormControl<any>(null),
        name: new FormControl<string>(''),
        sites: new FormControl<any>(null),
        order: new FormControl<string>(''),
      }),
    );
    this.acl = projectRepository.acl();
    effect(() => {
      this.acl.fetch(this.uid() || null);
    });
    effect(() => {
      const vals = this.acl();
      const value = this.value();
      const on = this.uid() ? vals?.specific : vals?.generic;
      setTimeout(() => {
        this.definedFixed.set(on?.fields?.noEditables || []);
        this.definedHidden.set(on?.fields?.noVisibles || []);
      });
    });
    this.siteProvider = siteRepository.selectorProvider(this.siteFilter);
    this.sitesProvider = siteRepository.selectorProvider(this.sitesFilter);
    this.defaultValues = () => {
      return {
        search: '',
        site: null,
        name: '',
        sites: null,
        order: '',
      };
    };
  }
}
