/* @autogenerated */
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { SiteViewListPageComponent } from './site-view-list-page.component';
import { SiteViewListModule } from '@features/organization/site/components/site-view-list/site-view-list.module';

const routes: Routes = [{ path: '', component: SiteViewListPageComponent }];
@NgModule({
  declarations: [SiteViewListPageComponent],
  imports: [RouterModule.forChild(routes), SiteViewListModule],
  exports: [RouterModule],
})
export class SiteViewListRouteModule {}
