/* @autogenerated */
import { ConfigTemplateViewFormGroupModule } from 'app/features/infrastructure/config-template/components/config-template-view-form-group/config-template-view-form-group.module';
import { ReactiveFormsModule } from '@angular/forms';
import { ConfigTemplateViewDetailComponent } from './config-template-view-detail.component';
import { provideTranslocoScope } from '@jsverse/transloco';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [ConfigTemplateViewDetailComponent],
  exports: [ConfigTemplateViewDetailComponent],
  imports: [ConfigTemplateViewFormGroupModule, ReactiveFormsModule],
  providers: [
    provideTranslocoScope({ scope: 'infrastructure/config-template', alias: 'infrastructure.config-template' }),
  ],
  bootstrap: [],
})
export class ConfigTemplateViewDetailModule {}
