/* @autogenerated */
import { SiteRepository } from 'app/features/organization/site/repository/site-repository.service';
import { FormControl } from '@angular/forms';
import { SiteProjection, SiteFilter } from 'app/features/organization/site/model/site.model';
import { Shift } from '@common/data/repository/repository.model';
import { input, effect, Component } from '@angular/core';

@Component({
  selector: 'site-view-list',
  templateUrl: './site-view-list.component.html',
  styleUrls: ['./site-view-list.component.scss'],
  standalone: false,
})
export class SiteViewListComponent {
  filters = input<SiteFilter>();
  actionName = input<string>('site');
  fixed = input<{ [key: string]: any }>();
  hidden = input<{ [key: string]: any }>();
  search = new FormControl<any>(undefined);
  list: Shift<SiteProjection[], SiteFilter>;

  constructor(repository: SiteRepository) {
    this.list = repository.projections(['client']);
    effect(() => {
      setTimeout(() => this.makeSearch());
    });
  }
  makeSearch() {
    const result = { limit: 10 } as any;
    const filter = this.search.value;
    const external = this.filters();
    if (external?.search) {
      result.search = external.search;
    }
    if (external?.name) {
      result.name = external.name;
    }
    if (external?.client) {
      result.client = external.client;
    }
    if (external?.clients) {
      result.clients = external.clients;
    }
    if (filter?.search) {
      result.search = filter.search;
    }
    if (filter?.name) {
      result.name = filter.name;
    }
    if (filter?.client?.$ref) {
      result.client = filter.client.$ref;
    }
    if (filter?.clients?.$ref) {
      result.clients = filter.clients.$ref;
    }
    if (filter?.order) {
      result.order = filter.order;
    }
    this.list.fetch(result);
  }

  next() {
    this.list.next();
  }

  reload() {
    this.list.reset();
  }

  prev() {
    console.log('PREV');
  }
}
