/* @autogenerated */
import { SiteViewStandarActionsModule } from 'app/features/organization/site/components/site-view-standar-actions/site-view-standar-actions.module';
import { SiteViewListComponent } from './site-view-list.component';
import { CommonModule } from '@angular/common';
import { ListViewModule } from '@common/toolkit/list-view/list-view.module';
import { TranslocoModule, provideTranslocoScope } from '@jsverse/transloco';
import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';
import { MatExpansionModule } from '@angular/material/expansion';
import { ReactiveFormsModule } from '@angular/forms';
import { SiteViewSearchModule } from '../site-view-search/site-view-search.module';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [SiteViewListComponent],
  exports: [SiteViewListComponent],
  imports: [
    CommonModule,
    ListViewModule,
    MatButtonModule,
    MatExpansionModule,
    MatIconModule,
    ReactiveFormsModule,
    SiteViewSearchModule,
    SiteViewStandarActionsModule,
    TranslocoModule,
  ],
  providers: [provideTranslocoScope({ scope: 'organization/site', alias: 'organization.site' })],
  bootstrap: [],
})
export class SiteViewListModule {}
