/* @autogenerated */
import { EditableTextComponent } from 'app/common/toolkit/editable/editable-text/editable-text.component';
import { EditableSelectoneComponent } from 'app/common/toolkit/editable/editable-selectone/editable-selectone.component';
import { EditableChooseComponent } from 'app/common/toolkit/editable/editable-choose/editable-choose.component';
import { MatInputModule } from '@angular/material/input';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { FormLayoutComponent } from 'app/common/toolkit/form-layout/form-layout.component';
import { ModelViewSearchComponent } from './model-view-search.component';
import { provideTranslocoScope } from '@jsverse/transloco';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [ModelViewSearchComponent],
  exports: [ModelViewSearchComponent],
  imports: [
    CommonModule,
    EditableChooseComponent,
    EditableSelectoneComponent,
    EditableTextComponent,
    FormLayoutComponent,
    FormsModule,
    MatInputModule,
    ReactiveFormsModule,
  ],
  providers: [provideTranslocoScope({ scope: 'infrastructure/model', alias: 'infrastructure.model' })],
  bootstrap: [],
})
export class ModelViewSearchModule {}
