/* @autogenerated */
import { TranslocoService } from '@jsverse/transloco';
import { ActionContainerComponent } from 'app/common/toolkit/action/action-container.component';
import { Action } from 'app/common/toolkit/action/action.model';
import { Tick } from 'app/common/data/repository/repository.model';
import { ProjectRepository } from 'app/features/installations/project/repository/project-repository.service';
import { Acl } from 'app/common/data/acl/acl.model';
import { Project } from 'app/features/installations/project/model/project.model';
import { computed, input, viewChild, Component, signal, TemplateRef } from '@angular/core';

@Component({
  selector: 'project-view-inventario',
  standalone: false,
  templateUrl: './project-view-inventario.component.html',
  styleUrl: './project-view-inventario.component.scss',
})
export class ProjectViewInventarioComponent implements Action {
  readonly name = 'inventario';
  readonly contextual = true;
  readonly multiple = false;
  container = signal<ActionContainerComponent | undefined>(undefined);
  selection = signal<any[]>([]);
  render = viewChild<TemplateRef<any>>('formTemplate');

  title = signal<string>('inventario');
  label = signal<string>('inventario');
  icon = signal<string>('gavel');
  tooltip = signal<string>('inventario');
  default = input<boolean>(false);

  visibleValue = signal(true);
  enabledValue = signal(true);

  constructor(
    private readonly repository: ProjectRepository,
    transloco: TranslocoService,
  ) {
    transloco.selectTranslateObject('action.inventario', {}, 'installations/project').subscribe((val) => {
      if (val.label) {
        this.label.set(val.label);
      }
      if (val.tooltip) {
        this.tooltip.set(val.tooltip);
      }
      if (val.icon) {
        this.icon.set(val.icon);
      }
      if (val.title) {
        this.title.set(val.title);
      }
    });
  }

  visible(items: any[]) {
    return this.visibleValue;
  }

  enabled(items: any[]) {
    return this.enabledValue;
  }
  run(): void {}
}
