/* @autogenerated */
import { TranslocoModule, provideTranslocoScope } from '@jsverse/transloco';
import { CommonModule } from '@angular/common';
import { ProjectViewInventarioComponent } from './project-view-inventario.component';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [ProjectViewInventarioComponent],
  exports: [ProjectViewInventarioComponent],
  imports: [CommonModule, TranslocoModule],
  providers: [provideTranslocoScope({ scope: 'installations/project', alias: 'installations.project' })],
  bootstrap: [],
})
export class ProjectViewInventarioModule {}
