/* @autogenerated */
import { TranslocoService } from '@jsverse/transloco';
import { ActionContainerComponent } from 'app/common/toolkit/action/action-container.component';
import { Action } from 'app/common/toolkit/action/action.model';
import { Tick } from 'app/common/data/repository/repository.model';
import { Acl } from 'app/common/data/acl/acl.model';
import { Model } from 'app/features/infrastructure/model/model/model.model';
import { Subscription } from 'rxjs';
import { MatSnackBar } from '@angular/material/snack-bar';
import { MatDialog, MatDialogRef } from '@angular/material/dialog';
import { ModelRepository } from 'app/features/infrastructure/model/repository/model-repository.service';
import { LongTaskViewComponent } from 'app/common/toolkit/long-task-view/long-task-view.component';
import { OnDestroy, input, viewChild, Component, signal, TemplateRef } from '@angular/core';

@Component({
  selector: 'model-view-delete-selection-action',
  standalone: false,
  templateUrl: './model-view-delete-selection-action.component.html',
  styleUrl: './model-view-delete-selection-action.component.scss',
})
export class ModelViewDeleteSelectionActionComponent implements Action, OnDestroy {
  readonly name = 'deleteSelection';
  readonly contextual = true;
  readonly multiple = true;
  container = signal<ActionContainerComponent | undefined>(undefined);
  selection = signal<any[]>([]);
  render = signal<TemplateRef<any> | undefined>(undefined);
  dialogTemplate = viewChild<TemplateRef<any>>('dialogTemplate');

  title = signal<string>('Borrando el item');
  label = signal<string>('Delete');
  icon = signal<string>('delete');
  tooltip = signal<string>('Borra el elemento seleccionado');
  default = input<boolean>(false);

  visibleValue = signal(false);
  enabledValue = signal(true);

  acl: Tick<{ generic: Acl; specific: Acl }, string | null>;

  private dialgoRef?: MatDialogRef<any, any>;
  private dialogSubs?: Subscription;
  private dismiss = 'Close';
  private report = 'Deleted...';
  private progress = 'Deleted...';

  constructor(
    private readonly repository: ModelRepository,
    private readonly dialog: MatDialog,
    private readonly snakeBar: MatSnackBar,
    transloco: TranslocoService,
  ) {
    this.acl = repository.acl();
    this.acl.fetch(null).subscribe((info) => {
      this.visibleValue.set(this.allowed(info?.generic));
    });
    transloco.selectTranslateObject('action.delete-selection', {}, 'infrastructure/model').subscribe((val) => {
      if (val.label) {
        this.label.set(val.label);
      }
      if (val.tooltip) {
        this.tooltip.set(val.tooltip);
      }
      if (val.icon) {
        this.icon.set(val.icon);
      }
      if (val.title) {
        this.title.set(val.title);
      }
      if (val.dismiss) {
        this.dismiss = val.dismiss;
      }
      if (val.report) {
        this.report = val.report;
      }
      if (val.progress) {
        this.progress = val.progress;
      }
    });
  }

  visible(items: any[]) {
    return this.visibleValue;
  }

  enabled(items: any[]) {
    return this.enabledValue;
  }
  run(): void {
    const template = this.dialogTemplate();
    if (template) {
      this.dialgoRef?.close();
      this.dialgoRef = this.dialog.open(template);
      this.dialogSubs = this.dialgoRef.afterClosed().subscribe((val) => {
        if (val) {
          this.deleteSelection(this.selection());
        } else {
          this.container()?.close();
        }
      });
    }
  }

  ngOnDestroy(): void {
    this.dialgoRef?.close();
    this.dialogSubs?.unsubscribe();
  }

  private deleteSelection(items: Model[]) {
    const filter = { uids: items.map((item) => item.uid) };
    this.dialgoRef = this.dialog.open(LongTaskViewComponent, {
      data: {
        title: this.progress,
        progress: this.repository.deleteSelection(filter),
      },
    });
    this.dialogSubs = this.dialgoRef.afterClosed().subscribe((val) => {
      this.container()?.selectionModel.clearSelection();
      this.container()?.close();
      this.snakeBar.open(this.report, this.dismiss, { duration: 5000 });
    });
  }
  private allowed(allow: Acl | undefined) {
    return this.repository.canDeleteSelection() && !!allow?.allows?.find((info) => info.name == 'delete')?.allowed;
  }
}
