/* @autogenerated */
import { MatDialogModule } from '@angular/material/dialog';
import { MatSnackBarModule } from '@angular/material/snack-bar';
import { TranslocoModule, provideTranslocoScope } from '@jsverse/transloco';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { FloorViewFormGroupModule } from 'app/features/organization/floor/components/floor-view-form-group/floor-view-form-group.module';
import { FloorViewDeleteSelectionActionComponent } from './floor-view-delete-selection-action.component';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [FloorViewDeleteSelectionActionComponent],
  exports: [FloorViewDeleteSelectionActionComponent],
  imports: [
    CommonModule,
    FloorViewFormGroupModule,
    MatButtonModule,
    MatDialogModule,
    MatSnackBarModule,
    ReactiveFormsModule,
    TranslocoModule,
  ],
  providers: [provideTranslocoScope({ scope: 'organization/floor', alias: 'organization.floor' })],
  bootstrap: [],
})
export class FloorViewDeleteSelectionActionModule {}
