/* @autogenerated */
import { ChangeDetectionStrategy, Component, Inject } from '@angular/core';
import { MatDialogRef, MAT_DIALOG_DATA, MatDialogModule } from '@angular/material/dialog';
import { Router } from '@angular/router';
import { ErrorPageComponent } from '../error-page/error-page.component';
import { MatIconModule } from '@angular/material/icon';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'error-modal',
  standalone: true,
  imports: [CommonModule, MatDialogModule, MatIconModule, ErrorPageComponent],
  templateUrl: './error-modal.component.html',
  styleUrls: ['./error-modal.component.css'],
})
export class ErrorModalComponent {
  loading = false;
  isLogged = false;
  retryError: any;
  retrySuccess: any;
  showBody = true;
  constructor(
    private router: Router,
    public dialogRef: MatDialogRef<ErrorModalComponent>,
    @Inject(MAT_DIALOG_DATA) public data: any,
  ) {
    this.isLogged = false;
  }
  public close() {
    this.data.notify = true;
    this.dialogRef.close(this.data);
  }
  public redirect(path: string) {
    this.dialogRef.close();
    this.router.navigate([path]);
  }
}
