/* @autogenerated */
import { Routes, ROUTES } from '@angular/router';
import { AppConfigService, MicroFrontConfigService } from '@common/context/config/app-config.service';
import { menuRoutes } from './menu.config';
import { UnknownComponent } from './layout/pages/unknown/unknown.component';
import { HomeComponent } from './layout/pages/home/home.component';
import { ContainerComponent } from './layout/pages/container/container.component';

export function provideConfiguredRoutes() {
  function initializeRoutes(appConfig: AppConfigService, mfeConfig: MicroFrontConfigService) {
    return [
      {
        path: ':language/:tenant',
        component: ContainerComponent,
        runGuardsAndResolvers: 'paramsOrQueryParamsChange',
        children: aditioanlRoutes(appConfig, mfeConfig),
      },
      {
        path: '',
        component: HomeComponent,
      },
      {
        path: '**',
        component: UnknownComponent,
      },
    ];
  }
  return {
    provide: ROUTES,
    useFactory: initializeRoutes,
    deps: [AppConfigService, MicroFrontConfigService],
    multi: true,
  };
}

function aditioanlRoutes(appConfig: AppConfigService, mfeConfig: MicroFrontConfigService): Routes {
  const base = menuRoutes(appConfig, mfeConfig);
  return [
    ...base,
    {
      path: '**',
      component: UnknownComponent,
    },
  ];
}
