/* @autogenerated */
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { FloorViewListPageComponent } from './floor-view-list-page.component';
import { FloorViewListModule } from '@features/organization/floor/components/floor-view-list/floor-view-list.module';

const routes: Routes = [{ path: '', component: FloorViewListPageComponent }];
@NgModule({
  declarations: [FloorViewListPageComponent],
  imports: [RouterModule.forChild(routes), FloorViewListModule],
  exports: [RouterModule],
})
export class FloorViewListRouteModule {}
