/* @autogenerated */
import { Client } from '../model/client.model';
import { Observable, of } from 'rxjs';
export function appwriteDataNormalizer(data: Client): Observable<Client> {
  const copy = { ...data } as any;
  return of(copy);
}
