/* @autogenerated */
import { Client } from '../model/client.model';
import { Observable, of } from 'rxjs';
export function appwriteReader(data: any): Client {
  const copy = { ...data } as any;
  return copy;
}
