/* @autogenerated */
import { ClientFilter } from '../model/client.model';
import { Observable, of } from 'rxjs';
export function appwriteQuery(query: ClientFilter): Observable<string[]> {
  const constraints: string[] = [];
  return of(constraints);
}
