/* @autogenerated */
import { appwriteQuery } from './appwrite-query.method';
import { DisplayProvider } from '@common/data/display-provider';
import { appwriteAcl } from './appwrite-acl.method';
import { selectorProvider, SelectorProvider } from '@common/data/selector-provider';
import { Acl } from '@common/data/acl/acl.model';
import { RepositoryMetadata, RepositoryService } from '@common/data/repository/repository.service';
import { appwriteReader } from './appwrite-reader.method';
import { appwriteDataNormalizer } from './appwrite-data-normalizer.method';
import { Slide } from '@common/data/repository/provider/repository-provider.interface';
import { AppwriteDataBuilder } from '@common/appwrite/data/appwrite-data-builder.service';
import { ClientFilter, ClientProjection, Client } from '@features/organization/client/model/client.model';
import { Observable, of } from 'rxjs';
import { Shift, Tick } from '@common/data/repository/repository.model';
import { Injectable, Signal } from '@angular/core';

@Injectable({ providedIn: 'root' })
export class ClientRepository {
  private readonly repo: RepositoryService<Client, ClientFilter>;
  public static metadata(api: AppwriteDataBuilder): RepositoryMetadata<Client, ClientFilter> {
    return {
      key: 'uid',
      name: 'client',
      provider: api.provider(
        'uid',
        'netconfighub_documents',
        'netconfighub_client',
        'netconfighub_attacheds',
        appwriteAcl,
        appwriteQuery,
        appwriteReader,
        appwriteDataNormalizer,
      ),
      reference: (name: string): RepositoryService<any, any> | null => {
        return null;
      },
    };
  }
  constructor(api: AppwriteDataBuilder) {
    this.repo = new RepositoryService(ClientRepository.metadata(api));
  }
  acl(): Tick<{ generic: Acl; specific: Acl }, string | null> {
    return this.repo.acl();
  }
  checkAcl(key?: string): Observable<Acl> {
    return this.repo.checkAcl(key || null);
  }
  generateComb(): string {
    return this.repo.generateComb();
  }

  add(item: Client): Observable<Client> {
    item['uid'] = this.generateComb();
    return this.repo.add(item);
  }
  update(item: Client): Observable<Client> {
    return this.repo.update(item);
  }
  deleteByKey(item: string): Observable<void> {
    return this.repo.deleteByKey(item);
  }
  canDeleteSelection(): boolean {
    return this.repo.canDeleteSelection();
  }
  deleteSelection(filter: ClientFilter): Observable<any> {
    return this.repo.deleteSelection(this.publicQueryFilter(filter));
  }
  retrieve(code: string): Observable<Client | undefined> {
    return this.repo.retrieve(code);
  }
  projection(includes: string[]): Tick<ClientProjection, string> {
    return this.repo.projection(includes);
  }
  list(filter: ClientFilter): Observable<Slide<Client>> {
    return this.repo.list(this.publicQueryFilter(filter));
  }
  values(filter: ClientFilter): Observable<Client[]> {
    return this.repo.values(this.publicQueryFilter(filter));
  }
  projections(includes: string[]): Shift<ClientProjection[], ClientFilter> {
    return this.repo.projections(includes);
  }
  enable(key: string): Observable<Client> {
    return this.repo.partialByKey(
      key,
      {
        enabled: true,
      },
      'enable',
    );
  }
  canEnableSelection() {
    return this.repo.canUsePartialsByKey();
  }
  enableSelection(filter: ClientFilter) {
    return this.repo.partialBySelection(this.publicQueryFilter(filter), { enabled: true }, 'enable');
  }
  disable(key: string): Observable<Client> {
    return this.repo.partialByKey(
      key,
      {
        enabled: false,
      },
      'disable',
    );
  }
  canDisableSelection() {
    return this.repo.canUsePartialsByKey();
  }
  disableSelection(filter: ClientFilter) {
    return this.repo.partialBySelection(this.publicQueryFilter(filter), { enabled: false }, 'disable');
  }
  displayProvider(): DisplayProvider<Client> {
    return {
      display: (item: Client) => {
        return item.name!;
      },
    };
  }
  selectorProvider(filter?: Signal<ClientFilter>): SelectorProvider<Client, { $ref: string }> {
    return selectorProvider({
      search: (text: string) => {
        const filterValue = filter ? filter() : { limit: 10 };
        filterValue.search = text;
        return this.values(filterValue);
      },
      display: (item: Client) => {
        return item.name!;
      },
      value: (item: Client) => {
        return { $ref: item.uid!, $id: (item as any).$id };
      },
      select: (ref: { $ref: string }) => {
        return ref['$ref'] ? this.retrieve(ref['$ref']) : of(undefined);
      },
      equals: (one: { $ref: string }, other: { $ref: string }) => {
        return one.$ref === other.$ref;
      },
    });
  }
  private publicQueryFilter(filter: ClientFilter): ClientFilter {
    const morphed = {} as any;
    if (filter.search) {
      morphed['search'] = filter.search;
    }
    if (filter.uids) {
      morphed['uids'] = filter.uids.join(',');
    }
    if (filter.limit) {
      morphed['limit'] = filter.limit;
    }
    if (filter.order) {
      morphed['order'] = filter.order;
    }
    if (filter.name) {
      morphed['name'] = filter.name;
    }
    return morphed;
  }
}
