/* @autogenerated */
import { TypeFilter } from '../model/type.model';
import { Observable, of } from 'rxjs';
export function appwriteQuery(query: TypeFilter): Observable<string[]> {
  const constraints: string[] = [];
  return of(constraints);
}
