/* @autogenerated */
import { Type } from '../model/type.model';
import { Observable, of } from 'rxjs';
export function appwriteDataNormalizer(data: Type): Observable<Type> {
  const copy = { ...data } as any;
  return of(copy);
}
