/* @autogenerated */
import { Type } from '../model/type.model';
import { Observable, of } from 'rxjs';
export function appwriteReader(data: any): Type {
  const copy = { ...data } as any;
  return copy;
}
