/* @autogenerated */
import { Query } from 'appwrite';
import { TypeFilter } from '../model/type.model';
import { Observable, of } from 'rxjs';
export function appwriteQuery(query: TypeFilter): Observable<string[]> {
  const constraints: string[] = [];
  if (query.name) {
    constraints.push(Query.equal('name', query.name as any));
  }
  return of(constraints);
}
