/* @autogenerated */
import { QueryConstraint, where } from 'firebase/firestore';
import { Type } from '../model/type.model';
import { Observable, of } from 'rxjs';
export function firebaseDataNormalizer(data: Type): Observable<Type> {
  return of(data);
}
