/* @autogenerated */
import { QueryConstraint, where } from 'firebase/firestore';
import { TypeFilter } from '../model/type.model';
import { Observable, of } from 'rxjs';
export function firebaseQuery(query: TypeFilter): Observable<QueryConstraint[]> {
  const constraints: QueryConstraint[] = [];
  return of(constraints);
}
