/* @autogenerated */
import { appwriteQuery } from './appwrite-query.method';
import { DisplayProvider } from '@common/data/display-provider';
import { appwriteAcl } from './appwrite-acl.method';
import { selectorProvider, SelectorProvider } from '@common/data/selector-provider';
import { Acl } from '@common/data/acl/acl.model';
import { RepositoryMetadata, RepositoryService } from '@common/data/repository/repository.service';
import { appwriteReader } from './appwrite-reader.method';
import { appwriteDataNormalizer } from './appwrite-data-normalizer.method';
import { Slide } from '@common/data/repository/provider/repository-provider.interface';
import { AppwriteDataBuilder } from '@common/appwrite/data/appwrite-data-builder.service';
import { TypeProjection, TypeFilter, Type } from '@features/infrastructure/type/model/type.model';
import { Observable, of } from 'rxjs';
import { Shift, Tick } from '@common/data/repository/repository.model';
import { Injectable, Signal } from '@angular/core';

@Injectable({ providedIn: 'root' })
export class TypeRepository {
  private readonly repo: RepositoryService<Type, TypeFilter>;
  public static metadata(api: AppwriteDataBuilder): RepositoryMetadata<Type, TypeFilter> {
    return {
      key: 'uid',
      name: 'type',
      provider: api.provider(
        'uid',
        'netconfighub_documents',
        'netconfighub_type',
        'netconfighub_attacheds',
        appwriteAcl,
        appwriteQuery,
        appwriteReader,
        appwriteDataNormalizer,
      ),
      reference: (name: string): RepositoryService<any, any> | null => {
        return null;
      },
    };
  }
  constructor(api: AppwriteDataBuilder) {
    this.repo = new RepositoryService(TypeRepository.metadata(api));
  }
  acl(): Tick<{ generic: Acl; specific: Acl }, string | null> {
    return this.repo.acl();
  }
  checkAcl(key?: string): Observable<Acl> {
    return this.repo.checkAcl(key || null);
  }
  generateComb(): string {
    return this.repo.generateComb();
  }

  add(item: Type): Observable<Type> {
    item['uid'] = this.generateComb();
    return this.repo.add(item);
  }
  update(item: Type): Observable<Type> {
    return this.repo.update(item);
  }
  deleteByKey(item: string): Observable<void> {
    return this.repo.deleteByKey(item);
  }
  canDeleteSelection(): boolean {
    return this.repo.canDeleteSelection();
  }
  deleteSelection(filter: TypeFilter): Observable<any> {
    return this.repo.deleteSelection(this.publicQueryFilter(filter));
  }
  retrieve(code: string): Observable<Type | undefined> {
    return this.repo.retrieve(code);
  }
  projection(includes: string[]): Tick<TypeProjection, string> {
    return this.repo.projection(includes);
  }
  list(filter: TypeFilter): Observable<Slide<Type>> {
    return this.repo.list(this.publicQueryFilter(filter));
  }
  values(filter: TypeFilter): Observable<Type[]> {
    return this.repo.values(this.publicQueryFilter(filter));
  }
  projections(includes: string[]): Shift<TypeProjection[], TypeFilter> {
    return this.repo.projections(includes);
  }
  displayProvider(): DisplayProvider<Type> {
    return {
      display: (item: Type) => {
        return item.name!;
      },
    };
  }
  selectorProvider(filter?: Signal<TypeFilter>): SelectorProvider<Type, { $ref: string }> {
    return selectorProvider({
      search: (text: string) => {
        const filterValue = filter ? filter() : { limit: 10 };
        filterValue.search = text;
        return this.values(filterValue);
      },
      display: (item: Type) => {
        return item.name!;
      },
      value: (item: Type) => {
        return { $ref: item.uid!, $id: (item as any).$id };
      },
      select: (ref: { $ref: string }) => {
        return ref['$ref'] ? this.retrieve(ref['$ref']) : of(undefined);
      },
      equals: (one: { $ref: string }, other: { $ref: string }) => {
        return one.$ref === other.$ref;
      },
    });
  }
  private publicQueryFilter(filter: TypeFilter): TypeFilter {
    const morphed = {} as any;
    if (filter.search) {
      morphed['search'] = filter.search;
    }
    if (filter.uids) {
      morphed['uids'] = filter.uids.join(',');
    }
    if (filter.limit) {
      morphed['limit'] = filter.limit;
    }
    if (filter.order) {
      morphed['order'] = filter.order;
    }
    if (filter.name) {
      morphed['name'] = filter.name;
    }
    return morphed;
  }
}
