/* @autogenerated */
import { SiteViewFormGroupModule } from 'app/features/organization/site/components/site-view-form-group/site-view-form-group.module';
import { ReactiveFormsModule } from '@angular/forms';
import { SiteViewDetailComponent } from './site-view-detail.component';
import { provideTranslocoScope } from '@jsverse/transloco';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [SiteViewDetailComponent],
  exports: [SiteViewDetailComponent],
  imports: [ReactiveFormsModule, SiteViewFormGroupModule],
  providers: [provideTranslocoScope({ scope: 'organization/site', alias: 'organization.site' })],
  bootstrap: [],
})
export class SiteViewDetailModule {}
