/* @autogenerated */
import { FormControl } from '@angular/forms';
import { Site } from 'app/features/organization/site/model/site.model';
import { input, effect, Component } from '@angular/core';

@Component({
  selector: 'site-view-detail',
  templateUrl: './site-view-detail.component.html',
  styleUrl: './site-view-detail.component.scss',
  standalone: false,
})
export class SiteViewDetailComponent {
  data = input.required<Site | null>();
  form = new FormControl<Site | undefined>({ value: undefined, disabled: true });

  public constructor() {
    effect(() => this.form.patchValue(this.data()));
  }
}
