/* @autogenerated */
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { TypeViewListPageComponent } from './type-view-list-page.component';
import { TypeViewListModule } from '@features/infrastructure/type/components/type-view-list/type-view-list.module';

const routes: Routes = [{ path: '', component: TypeViewListPageComponent }];
@NgModule({
  declarations: [TypeViewListPageComponent],
  imports: [RouterModule.forChild(routes), TypeViewListModule],
  exports: [RouterModule],
})
export class TypeViewListRouteModule {}
