/* @autogenerated */
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { ProjectDeviceViewListPageComponent } from './project-device-view-list-page.component';
import { ProjectDeviceViewListModule } from '@features/installations/project-device/components/project-device-view-list/project-device-view-list.module';

const routes: Routes = [{ path: '', component: ProjectDeviceViewListPageComponent }];
@NgModule({
  declarations: [ProjectDeviceViewListPageComponent],
  imports: [RouterModule.forChild(routes), ProjectDeviceViewListModule],
  exports: [RouterModule],
})
export class ProjectDeviceViewListRouteModule {}
