/* @autogenerated */
import { TranslocoService } from '@jsverse/transloco';
import { ActionContainerComponent } from 'app/common/toolkit/action/action-container.component';
import { Action } from 'app/common/toolkit/action/action.model';
import { Tick } from 'app/common/data/repository/repository.model';
import { Acl } from 'app/common/data/acl/acl.model';
import { FormControl } from '@angular/forms';
import { computed, input, viewChild, Component, signal, TemplateRef } from '@angular/core';
import { FloorRepository } from 'app/features/organization/floor/repository/floor-repository.service';
import { Floor } from 'app/features/organization/floor/model/floor.model';

@Component({
  selector: 'floor-view-edit-action',
  standalone: false,
  templateUrl: './floor-view-edit-action.component.html',
  styleUrl: './floor-view-edit-action.component.scss',
})
export class FloorViewEditActionComponent implements Action {
  readonly name = 'edit';
  readonly contextual = true;
  readonly multiple = false;
  container = signal<ActionContainerComponent | undefined>(undefined);
  selection = signal<any[]>([]);
  render = viewChild<TemplateRef<any>>('formTemplate');

  title = signal<string>('Editando el item');
  label = signal<string>('Editar');
  icon = signal<string>('edit_note');
  tooltip = signal<string>('Edita el elemento seleccionado');
  default = input<boolean>(false);

  visibleValue = signal(false);
  enabledValue = signal(true);

  fixed = input<{ [key: string]: any }>();
  hidden = input<{ [key: string]: any }>();
  fixedProperties = computed(() => Object.keys(this.fixed() || {}));
  hiddenProperties = computed(() => Object.keys(this.hidden() || {}));
  definedProperties = computed(() => {
    return { ...(this.hidden() || {}), ...(this.fixed() || {}) };
  });
  form = new FormControl<Floor | undefined>(undefined);
  acl: Tick<{ generic: Acl; specific: Acl }, string | null>;
  constructor(
    private readonly repository: FloorRepository,
    transloco: TranslocoService,
  ) {
    this.acl = repository.acl();
    this.acl.fetch(null).subscribe((info) => {
      this.visibleValue.set(this.allowed(info?.generic));
    });
    transloco.selectTranslateObject('action.edit', {}, 'organization/floor').subscribe((val) => {
      if (val.label) {
        this.label.set(val.label);
      }
      if (val.tooltip) {
        this.tooltip.set(val.tooltip);
      }
      if (val.icon) {
        this.icon.set(val.icon);
      }
      if (val.title) {
        this.title.set(val.title);
      }
    });
  }

  visible(items: any[]) {
    return this.visibleValue;
  }

  enabled(items: any[]) {
    return this.enabledValue;
  }
  run(): void {
    this.form.patchValue(this.selection()[0]);
  }
  save() {
    const value = this.form.value;
    if (!value) {
      throw Error('Unable to save without value');
    }
    this.repository.update(value).subscribe(() => this.container()?.close());
  }
  private allowed(allow: Acl | undefined) {
    return !!allow?.allows?.find((info) => info.name == 'create')?.allowed;
  }
}
