/* @autogenerated */
import { Component, ElementRef, Renderer2, ViewEncapsulation } from '@angular/core';
import { MAT_FORM_FIELD_DEFAULT_OPTIONS } from '@angular/material/form-field';

@Component({
  selector: 'form-layout',
  templateUrl: 'form-layout.component.html',
  styleUrl: 'form-layout.component.scss',
  standalone: true,
  encapsulation: ViewEncapsulation.None,
  providers: [{ provide: MAT_FORM_FIELD_DEFAULT_OPTIONS, useValue: { appearance: 'outline' } }],
})
export class FormLayoutComponent {
  public constructor(elRef: ElementRef, render: Renderer2) {
    render.addClass(elRef.nativeElement, 'form-layout-grid');
  }
}
