/* @autogenerated */
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { ModelViewListPageComponent } from './model-view-list-page.component';
import { ModelViewListModule } from '@features/infrastructure/model/components/model-view-list/model-view-list.module';

const routes: Routes = [{ path: '', component: ModelViewListPageComponent }];
@NgModule({
  declarations: [ModelViewListPageComponent],
  imports: [RouterModule.forChild(routes), ModelViewListModule],
  exports: [RouterModule],
})
export class ModelViewListRouteModule {}
