/* @autogenerated */
import { Component } from '@angular/core';

@Component({
  selector: 'model-view-list-page',
  template: '<model-view-list />',
  standalone: false,
  styles: [':host { flex: 1; display: flex; flex-direction: column; overflow: hidden; margin: 15px; }'],
})
export class ModelViewListPageComponent {}
