/* @autogenerated */
import { TranslocoModule, provideTranslocoScope } from '@jsverse/transloco';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { ProjectDeviceViewFormGroupModule } from 'app/features/installations/project-device/components/project-device-view-form-group/project-device-view-form-group.module';
import { ProjectDeviceViewCreateActionComponent } from './project-device-view-create-action.component';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [ProjectDeviceViewCreateActionComponent],
  exports: [ProjectDeviceViewCreateActionComponent],
  imports: [CommonModule, MatButtonModule, ProjectDeviceViewFormGroupModule, ReactiveFormsModule, TranslocoModule],
  providers: [provideTranslocoScope({ scope: 'installations/project-device', alias: 'installations.project-device' })],
  bootstrap: [],
})
export class ProjectDeviceViewCreateActionModule {}
