/* @autogenerated */
import { FloorViewStandarActionsModule } from 'app/features/organization/floor/components/floor-view-standar-actions/floor-view-standar-actions.module';
import { FloorViewListComponent } from './floor-view-list.component';
import { CommonModule } from '@angular/common';
import { ListViewModule } from '@common/toolkit/list-view/list-view.module';
import { TranslocoModule, provideTranslocoScope } from '@jsverse/transloco';
import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';
import { MatExpansionModule } from '@angular/material/expansion';
import { ReactiveFormsModule } from '@angular/forms';
import { FloorViewSearchModule } from '../floor-view-search/floor-view-search.module';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [FloorViewListComponent],
  exports: [FloorViewListComponent],
  imports: [
    CommonModule,
    FloorViewSearchModule,
    FloorViewStandarActionsModule,
    ListViewModule,
    MatButtonModule,
    MatExpansionModule,
    MatIconModule,
    ReactiveFormsModule,
    TranslocoModule,
  ],
  providers: [provideTranslocoScope({ scope: 'organization/floor', alias: 'organization.floor' })],
  bootstrap: [],
})
export class FloorViewListModule {}
