/* @autogenerated */
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { ConfigTemplateViewListPageComponent } from './config-template-view-list-page.component';
import { ConfigTemplateViewListModule } from '@features/infrastructure/config-template/components/config-template-view-list/config-template-view-list.module';

const routes: Routes = [{ path: '', component: ConfigTemplateViewListPageComponent }];
@NgModule({
  declarations: [ConfigTemplateViewListPageComponent],
  imports: [RouterModule.forChild(routes), ConfigTemplateViewListModule],
  exports: [RouterModule],
})
export class ConfigTemplateViewListRouteModule {}
