/* @autogenerated */
import { TranslocoModule, provideTranslocoScope } from '@jsverse/transloco';
import { CommonModule } from '@angular/common';
import { FloorViewListModule } from 'app/features/organization/floor/components/floor-view-list/floor-view-list.module';
import { SiteViewFloorsComponent } from './site-view-floors.component';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [SiteViewFloorsComponent],
  exports: [SiteViewFloorsComponent],
  imports: [CommonModule, FloorViewListModule, TranslocoModule],
  providers: [provideTranslocoScope({ scope: 'organization/site', alias: 'organization.site' })],
  bootstrap: [],
})
export class SiteViewFloorsModule {}
