/* @autogenerated */
import { TranslocoService } from '@jsverse/transloco';
import { ActionContainerComponent } from 'app/common/toolkit/action/action-container.component';
import { SiteRepository } from 'app/features/organization/site/repository/site-repository.service';
import { Action } from 'app/common/toolkit/action/action.model';
import { Site } from 'app/features/organization/site/model/site.model';
import { input, viewChild, Component, signal, TemplateRef } from '@angular/core';

@Component({
  selector: 'site-view-floors',
  standalone: false,
  templateUrl: './site-view-floors.component.html',
  styleUrl: './site-view-floors.component.scss',
})
export class SiteViewFloorsComponent implements Action {
  readonly name = 'floors';
  readonly contextual = true;
  readonly multiple = false;
  container = signal<ActionContainerComponent | undefined>(undefined);
  selection = signal<any[]>([]);
  render = viewChild<TemplateRef<any>>('formTemplate');

  title = signal<string>('floors');
  label = signal<string>('floors');
  icon = signal<string>('gavel');
  tooltip = signal<string>('floors');
  default = input<boolean>(false);

  visibleValue = signal(true);
  enabledValue = signal(true);

  constructor(
    private readonly repository: SiteRepository,
    transloco: TranslocoService,
  ) {
    transloco.selectTranslateObject('action.floors', {}, 'organization/site').subscribe((val) => {
      if (val.label) {
        this.label.set(val.label);
      }
      if (val.tooltip) {
        this.tooltip.set(val.tooltip);
      }
      if (val.icon) {
        this.icon.set(val.icon);
      }
      if (val.title) {
        this.title.set(val.title);
      }
    });
  }

  visible(items: any[]) {
    return this.visibleValue;
  }

  enabled(items: any[]) {
    return this.enabledValue;
  }
  run(): void {}
}
