/* @autogenerated */
import { Query } from 'appwrite';
import { ConfigTemplateFilter } from '../model/config-template.model';
import { Observable, of } from 'rxjs';
export function appwriteQuery(query: ConfigTemplateFilter): Observable<string[]> {
  const constraints: string[] = [];
  if (query.name) {
    constraints.push(Query.equal('name', query.name as any));
  }
  return of(constraints);
}
