/* @autogenerated */
import { ConfigTemplateFilter } from '../model/config-template.model';
import { Observable, of } from 'rxjs';
export function appwriteQuery(query: ConfigTemplateFilter): Observable<string[]> {
  const constraints: string[] = [];
  return of(constraints);
}
