/* @autogenerated */
import { ConfigTemplate } from '../model/config-template.model';
import { Observable, of } from 'rxjs';
export function appwriteDataNormalizer(data: ConfigTemplate): Observable<ConfigTemplate> {
  const copy = { ...data } as any;
  return of(copy);
}
