/* @autogenerated */
import { QueryConstraint, where } from 'firebase/firestore';
import { ConfigTemplate } from '../model/config-template.model';
import { Observable, of } from 'rxjs';
export function firebaseDataNormalizer(data: ConfigTemplate): Observable<ConfigTemplate> {
  return of(data);
}
