/* @autogenerated */
import { TranslocoService } from '@jsverse/transloco';
import { ActionContainerComponent } from 'app/common/toolkit/action/action-container.component';
import { Action } from 'app/common/toolkit/action/action.model';
import { ClientRepository } from 'app/features/organization/client/repository/client-repository.service';
import { Client } from 'app/features/organization/client/model/client.model';
import { input, viewChild, Component, signal, TemplateRef } from '@angular/core';

@Component({
  selector: 'client-view-sites',
  standalone: false,
  templateUrl: './client-view-sites.component.html',
  styleUrl: './client-view-sites.component.scss',
})
export class ClientViewSitesComponent implements Action {
  readonly name = 'sites';
  readonly contextual = true;
  readonly multiple = false;
  container = signal<ActionContainerComponent | undefined>(undefined);
  selection = signal<any[]>([]);
  render = viewChild<TemplateRef<any>>('formTemplate');

  title = signal<string>('sites');
  label = signal<string>('sites');
  icon = signal<string>('gavel');
  tooltip = signal<string>('sites');
  default = input<boolean>(false);

  visibleValue = signal(true);
  enabledValue = signal(true);

  constructor(
    private readonly repository: ClientRepository,
    transloco: TranslocoService,
  ) {
    transloco.selectTranslateObject('action.sites', {}, 'organization/client').subscribe((val) => {
      if (val.label) {
        this.label.set(val.label);
      }
      if (val.tooltip) {
        this.tooltip.set(val.tooltip);
      }
      if (val.icon) {
        this.icon.set(val.icon);
      }
      if (val.title) {
        this.title.set(val.title);
      }
    });
  }

  visible(items: any[]) {
    return this.visibleValue;
  }

  enabled(items: any[]) {
    return this.enabledValue;
  }
  run(): void {}
}
