/* @autogenerated */
import { ActionContainerComponent } from 'app/common/toolkit/action/action-container.component';
import { ProjectDeviceViewCreateActionModule } from 'app/features/installations/project-device/actions/project-device-view-create-action/project-device-view-create-action.module';
import { ProjectDeviceViewEditActionModule } from 'app/features/installations/project-device/actions/project-device-view-edit-action/project-device-view-edit-action.module';
import { ProjectDeviceViewDetailActionModule } from 'app/features/installations/project-device/actions/project-device-view-detail-action/project-device-view-detail-action.module';
import { ProjectDeviceViewDeleteActionModule } from 'app/features/installations/project-device/actions/project-device-view-delete-action/project-device-view-delete-action.module';
import { ProjectDeviceViewDeleteSelectionActionModule } from 'app/features/installations/project-device/actions/project-device-view-delete-selection-action/project-device-view-delete-selection-action.module';
import { ProjectDeviceViewStandarActionsComponent } from './project-device-view-standar-actions.component';
import { provideTranslocoScope } from '@jsverse/transloco';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [ProjectDeviceViewStandarActionsComponent],
  exports: [ProjectDeviceViewStandarActionsComponent],
  imports: [
    ActionContainerComponent,
    ProjectDeviceViewCreateActionModule,
    ProjectDeviceViewDeleteActionModule,
    ProjectDeviceViewDeleteSelectionActionModule,
    ProjectDeviceViewDetailActionModule,
    ProjectDeviceViewEditActionModule,
  ],
  providers: [provideTranslocoScope({ scope: 'installations/project-device', alias: 'installations.project-device' })],
  bootstrap: [],
})
export class ProjectDeviceViewStandarActionsModule {}
