/* @autogenerated */
import { ConfigTemplate } from 'app/features/infrastructure/config-template/model/config-template.model';
import { ConfigTemplateRepository } from 'app/features/infrastructure/config-template/repository/config-template-repository.service';
import { Tick } from 'app/common/data/repository/repository.model';
import { Acl } from 'app/common/data/acl/acl.model';
import { SubFormEditable } from 'app/common/toolkit/editable/subform-editable';
import { BaseEditable } from 'app/common/toolkit/editable/base-editable';
import { Validators, FormGroup, FormControl } from '@angular/forms';
import { effect, computed, Component } from '@angular/core';

@Component({
  selector: 'config-template-view-form-group',
  templateUrl: './config-template-view-form-group.component.html',
  styleUrls: ['./config-template-view-form-group.component.scss'],
  providers: BaseEditable.getValidableAccessorProvider(ConfigTemplateViewFormGroupComponent),
  standalone: false,
})
export class ConfigTemplateViewFormGroupComponent extends SubFormEditable<ConfigTemplate> {
  acl: Tick<{ generic: Acl; specific: Acl }, string | null>;
  uid = computed(() => this.value()?.uid);
  public constructor(configTemplateRepository: ConfigTemplateRepository) {
    super(
      new FormGroup({
        uid: new FormControl<string>(''),
        name: new FormControl<string>('', [Validators.required]),
        version: new FormControl<number>(0),
      }),
    );
    this.acl = configTemplateRepository.acl();
    effect(() => {
      this.acl.fetch(this.uid() || null);
    });
    effect(() => {
      const vals = this.acl();
      const value = this.value();
      const on = this.uid() ? vals?.specific : vals?.generic;
      setTimeout(() => {
        this.definedFixed.set(on?.fields?.noEditables || []);
        this.definedHidden.set(on?.fields?.noVisibles || []);
      });
    });
    this.defaultValues = () => {
      return {
        uid: '',
        name: '',
        version: 0,
      };
    };
  }
}
