/* @autogenerated */
import { Subscription } from 'rxjs';

export class Observer {
  private subscriptions: { [key: string]: Subscription } = {};

  public set(name: string, obs: Subscription) {
    this.subscriptions[name]?.unsubscribe();
    this.subscriptions[name] = obs;
  }

  public add(name: string, obs: Subscription) {
    if (!this.subscriptions[name]) {
      this.subscriptions[name] = new Subscription();
    }
    this.subscriptions[name].add(obs);
  }

  public unsubscribe() {
    Object.values(this.subscriptions).forEach((subs) => subs.unsubscribe());
  }
}
