/* @autogenerated */
import { Tick } from 'app/common/data/repository/repository.model';
import { Acl } from 'app/common/data/acl/acl.model';
import { SubFormEditable } from 'app/common/toolkit/editable/subform-editable';
import { TypeRepository } from 'app/features/infrastructure/type/repository/type-repository.service';
import { BaseEditable } from 'app/common/toolkit/editable/base-editable';
import { FormGroup, FormControl } from '@angular/forms';
import { effect, computed, Component } from '@angular/core';
import { Type } from 'app/features/infrastructure/type/model/type.model';

@Component({
  selector: 'type-view-search',
  templateUrl: './type-view-search.component.html',
  styleUrls: ['./type-view-search.component.scss'],
  providers: BaseEditable.getValidableAccessorProvider(TypeViewSearchComponent),
  standalone: false,
})
export class TypeViewSearchComponent extends SubFormEditable<any> {
  acl: Tick<{ generic: Acl; specific: Acl }, string | null>;
  uid = computed(() => this.value()?.uid);
  public constructor(typeRepository: TypeRepository) {
    super(
      new FormGroup({
        search: new FormControl<string>(''),
        name: new FormControl<string>(''),
        order: new FormControl<string>(''),
      }),
    );
    this.acl = typeRepository.acl();
    effect(() => {
      this.acl.fetch(this.uid() || null);
    });
    effect(() => {
      const vals = this.acl();
      const value = this.value();
      const on = this.uid() ? vals?.specific : vals?.generic;
      setTimeout(() => {
        this.definedFixed.set(on?.fields?.noEditables || []);
        this.definedHidden.set(on?.fields?.noVisibles || []);
      });
    });
    this.defaultValues = () => {
      return {
        search: '',
        name: '',
        order: '',
      };
    };
  }
}
