/* @autogenerated */
import { DeviceCheckFilter } from '../model/device-check.model';
import { Observable, of } from 'rxjs';
export function appwriteQuery(query: DeviceCheckFilter): Observable<string[]> {
  const constraints: string[] = [];
  return of(constraints);
}
