/* @autogenerated */
import { DeviceCheck } from '../model/device-check.model';
import { Observable, of } from 'rxjs';
export function appwriteReader(data: any): DeviceCheck {
  const copy = { ...data } as any;
  copy.projectDevice = { $ref: data.projectDevice, $id: (data as any).projectDevice?.$id };
  return copy;
}
