/* @autogenerated */
import {
  DeviceCheck,
  DeviceCheckProjection,
  DeviceCheckFilter,
} from '@features/installations/device-check/model/device-check.model';
import { DisplayProvider } from '@common/data/display-provider';
import { ApiProvider } from '@common/data/repository/provider/impl/api.provider';
import { ApiService } from '@common/data/api/api.service';
import { selectorProvider, SelectorProvider } from '@common/data/selector-provider';
import { Acl } from '@common/data/acl/acl.model';
import { Observable, of } from 'rxjs';
import { RepositoryMetadata, RepositoryService } from '@common/data/repository/repository.service';
import { Shift, Tick } from '@common/data/repository/repository.model';
import { Injectable, Signal } from '@angular/core';
import { ProjectDeviceRepository } from '@features/installations/project-device/repository/project-device-repository.service';
import { Slide } from '@common/data/repository/provider/repository-provider.interface';

@Injectable({ providedIn: 'root' })
export class DeviceCheckRepository {
  private readonly repo: RepositoryService<DeviceCheck, DeviceCheckFilter>;
  public static metadata(api: ApiService): RepositoryMetadata<DeviceCheck, DeviceCheckFilter> {
    return {
      key: 'uid',
      name: 'device-check',
      provider: new ApiProvider(
        'uid',
        api,
        'http://net-civeira-netconfighub/installations/device-checks',
        'http://net-civeira-netconfighub/me/acl/installations/device-checks',
      ),
      reference: (name: string): RepositoryService<any, any> | null => {
        if ('projectDevice' == name) {
          return new RepositoryService(ProjectDeviceRepository.metadata(api));
        }
        return null;
      },
    };
  }
  constructor(api: ApiService) {
    this.repo = new RepositoryService(DeviceCheckRepository.metadata(api));
  }
  acl(): Tick<{ generic: Acl; specific: Acl }, string | null> {
    return this.repo.acl();
  }
  checkAcl(key?: string): Observable<Acl> {
    return this.repo.checkAcl(key || null);
  }
  generateComb(): string {
    return this.repo.generateComb();
  }

  add(item: DeviceCheck): Observable<DeviceCheck> {
    item['uid'] = this.generateComb();
    return this.repo.add(item);
  }
  update(item: DeviceCheck): Observable<DeviceCheck> {
    return this.repo.update(item);
  }
  deleteByKey(item: string): Observable<void> {
    return this.repo.deleteByKey(item);
  }
  canDeleteSelection(): boolean {
    return this.repo.canDeleteSelection();
  }
  deleteSelection(filter: DeviceCheckFilter): Observable<any> {
    return this.repo.deleteSelection(this.publicQueryFilter(filter));
  }
  retrieve(code: string): Observable<DeviceCheck | undefined> {
    return this.repo.retrieve(code);
  }
  projection(includes: string[]): Tick<DeviceCheckProjection, string> {
    return this.repo.projection(includes);
  }
  list(filter: DeviceCheckFilter): Observable<Slide<DeviceCheck>> {
    return this.repo.list(this.publicQueryFilter(filter));
  }
  values(filter: DeviceCheckFilter): Observable<DeviceCheck[]> {
    return this.repo.values(this.publicQueryFilter(filter));
  }
  projections(includes: string[]): Shift<DeviceCheckProjection[], DeviceCheckFilter> {
    return this.repo.projections(includes);
  }
  displayProvider(): DisplayProvider<DeviceCheck> {
    return {
      display: (item: DeviceCheck) => {
        return item.result!;
      },
    };
  }
  selectorProvider(filter?: Signal<DeviceCheckFilter>): SelectorProvider<DeviceCheck, { $ref: string }> {
    return selectorProvider({
      search: (text: string) => {
        const filterValue = filter ? filter() : { limit: 10 };
        filterValue.search = text;
        return this.values(filterValue);
      },
      display: (item: DeviceCheck) => {
        return item.result!;
      },
      value: (item: DeviceCheck) => {
        return { $ref: item.uid! };
      },
      select: (ref: { $ref: string }) => {
        return ref['$ref'] ? this.retrieve(ref['$ref']) : of(undefined);
      },
      equals: (one: { $ref: string }, other: { $ref: string }) => {
        return one.$ref === other.$ref;
      },
    });
  }
  private publicQueryFilter(filter: DeviceCheckFilter): DeviceCheckFilter {
    const morphed = {} as any;
    if (filter.search) {
      morphed['search'] = filter.search;
    }
    if (filter.uids) {
      morphed['uids'] = filter.uids.join(',');
    }
    if (filter.limit) {
      morphed['limit'] = filter.limit;
    }
    if (filter.order) {
      morphed['order'] = filter.order;
    }
    if (filter.result) {
      morphed['result'] = filter.result;
    }
    if (filter.projectDevice) {
      morphed['project-device'] = filter.projectDevice;
    }
    if (filter.projectDevices) {
      morphed['project-devices'] = filter.projectDevices;
    }
    return morphed;
  }
}
