/* @autogenerated */
import { QueryConstraint, where } from 'firebase/firestore';
import { DeviceCheckFilter } from '../model/device-check.model';
import { Observable, of } from 'rxjs';
export function firebaseQuery(query: DeviceCheckFilter): Observable<QueryConstraint[]> {
  const constraints: QueryConstraint[] = [];
  return of(constraints);
}
