/* @autogenerated */
import { NgModule } from '@angular/core';
import { OidcIdentityProviderService } from './oidc-identity-provider.service';
import { OAuthModule, OAuthService } from 'angular-oauth2-oidc';
import { IDENTITY_PROVIDER } from '../identity-provider.interface';
import { AppConfigService } from '@common/context/config/app-config.service';
import { AppStateService } from '@common/context/state/app-state.service';
import { ErrorService } from '@common/context/observability/error.service';

@NgModule({
  imports: [OAuthModule.forRoot()],
  exports: [],
  providers: [
    {
      provide: IDENTITY_PROVIDER,
      useClass: OidcIdentityProviderService,
      multi: true,
      deps: [OAuthService, AppConfigService, AppStateService, ErrorService],
    },
  ],
})
export class OidcLoginModule {}
