/* @autogenerated */
import { TranslocoModule, provideTranslocoScope } from '@jsverse/transloco';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { ModelViewFormGroupModule } from 'app/features/infrastructure/model/components/model-view-form-group/model-view-form-group.module';
import { ModelViewCreateActionComponent } from './model-view-create-action.component';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [ModelViewCreateActionComponent],
  exports: [ModelViewCreateActionComponent],
  imports: [CommonModule, MatButtonModule, ModelViewFormGroupModule, ReactiveFormsModule, TranslocoModule],
  providers: [provideTranslocoScope({ scope: 'infrastructure/model', alias: 'infrastructure.model' })],
  bootstrap: [],
})
export class ModelViewCreateActionModule {}
