/* @autogenerated */
import { Project } from '../model/project.model';
import { Observable, of } from 'rxjs';
export function appwriteReader(data: any): Project {
  const copy = { ...data } as any;
  copy.site = { $ref: data.site, $id: (data as any).site?.$id };
  return copy;
}
