/* @autogenerated */
import { AbstactContainerWrapper } from 'app/common/toolkit/action/abstract-container-wrapper';
import { ItemMapper, ActionContainerComponent } from 'app/common/toolkit/action/action-container.component';
import { Tick } from 'app/common/data/repository/repository.model';
import { Acl } from 'app/common/data/acl/acl.model';
import { ModelProjection } from 'app/features/infrastructure/model/model/model.model';
import { ModelRepository } from 'app/features/infrastructure/model/repository/model-repository.service';
import { input, computed, effect, viewChild, Component } from '@angular/core';

@Component({
  standalone: false,
  selector: 'model-view-standar-actions',
  templateUrl: './model-view-standar-actions.component.html',
  styleUrl: './model-view-standar-actions.component.scss',
})
export class ModelViewStandarActionsComponent extends AbstactContainerWrapper {
  override actions = viewChild<ActionContainerComponent>('container');
  fixed = input<{ [key: string]: any }>();
  hidden = input<{ [key: string]: any }>();

  activated: Tick<ModelProjection, string>;
  acl: Tick<{ generic: Acl; specific: Acl }, string | null>;

  mapper: ItemMapper<any>;

  constructor(public readonly repository: ModelRepository) {
    super();
    this.acl = this.repository.acl();
    this.activated = this.repository.projection([]);
    this.mapper = {
      display: (item: any) => {
        return item.uid;
      },
      load: (code: string) => {
        this.acl.fetch(code);
        this.activated.fetch(code);
        return this.activated;
      },
    };
    effect(() => {
      const selected = this.actions()?.selectionModel.selected();
      if (!selected || selected.length == 0) {
        this.acl.reset();
        this.activated.reset();
      }
    });
  }
}
