/* @autogenerated */
import { ActionContainerComponent } from 'app/common/toolkit/action/action-container.component';
import { ModelViewCreateActionModule } from 'app/features/infrastructure/model/actions/model-view-create-action/model-view-create-action.module';
import { ModelViewEditActionModule } from 'app/features/infrastructure/model/actions/model-view-edit-action/model-view-edit-action.module';
import { ModelViewDetailActionModule } from 'app/features/infrastructure/model/actions/model-view-detail-action/model-view-detail-action.module';
import { ModelViewDeleteActionModule } from 'app/features/infrastructure/model/actions/model-view-delete-action/model-view-delete-action.module';
import { ModelViewDeleteSelectionActionModule } from 'app/features/infrastructure/model/actions/model-view-delete-selection-action/model-view-delete-selection-action.module';
import { ModelViewStandarActionsComponent } from './model-view-standar-actions.component';
import { provideTranslocoScope } from '@jsverse/transloco';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [ModelViewStandarActionsComponent],
  exports: [ModelViewStandarActionsComponent],
  imports: [
    ActionContainerComponent,
    ModelViewCreateActionModule,
    ModelViewDeleteActionModule,
    ModelViewDeleteSelectionActionModule,
    ModelViewDetailActionModule,
    ModelViewEditActionModule,
  ],
  providers: [provideTranslocoScope({ scope: 'infrastructure/model', alias: 'infrastructure.model' })],
  bootstrap: [],
})
export class ModelViewStandarActionsModule {}
