/* @autogenerated */
import { SelectorProvider } from 'app/common/data/selector-provider';
import { ConfigTemplateRepository } from 'app/features/infrastructure/config-template/repository/config-template-repository.service';
import { Tick } from 'app/common/data/repository/repository.model';
import { Acl } from 'app/common/data/acl/acl.model';
import { ProjectDeviceRepository } from 'app/features/installations/project-device/repository/project-device-repository.service';
import { ProjectRepository } from 'app/features/installations/project/repository/project-repository.service';
import { SubFormEditable } from 'app/common/toolkit/editable/subform-editable';
import { Project, ProjectFilter } from 'app/features/installations/project/model/project.model';
import { ModelRepository } from 'app/features/infrastructure/model/repository/model-repository.service';
import { FloorRepository } from 'app/features/organization/floor/repository/floor-repository.service';
import {
  ConfigTemplate,
  ConfigTemplateFilter,
} from 'app/features/infrastructure/config-template/model/config-template.model';
import { Model, ModelFilter } from 'app/features/infrastructure/model/model/model.model';
import { TypeRepository } from 'app/features/infrastructure/type/repository/type-repository.service';
import { ProjectDevice } from 'app/features/installations/project-device/model/project-device.model';
import { BaseEditable } from 'app/common/toolkit/editable/base-editable';
import { FormGroup, FormControl } from '@angular/forms';
import { effect, computed, Component, input } from '@angular/core';
import { Type, TypeFilter } from 'app/features/infrastructure/type/model/type.model';
import { Floor, FloorFilter } from 'app/features/organization/floor/model/floor.model';

@Component({
  selector: 'project-device-view-search',
  templateUrl: './project-device-view-search.component.html',
  styleUrls: ['./project-device-view-search.component.scss'],
  providers: BaseEditable.getValidableAccessorProvider(ProjectDeviceViewSearchComponent),
  standalone: false,
})
export class ProjectDeviceViewSearchComponent extends SubFormEditable<any> {
  acl: Tick<{ generic: Acl; specific: Acl }, string | null>;
  uid = computed(() => this.value()?.uid);
  modelsProvider: SelectorProvider<Model, { $ref: string }>;
  modelsFilter = input<ModelFilter>({ limit: 100 });
  typesProvider: SelectorProvider<Type, { $ref: string }>;
  typesFilter = input<TypeFilter>({ limit: 100 });
  projectsProvider: SelectorProvider<Project, { $ref: string }>;
  projectsFilter = input<ProjectFilter>({ limit: 100 });
  projectProvider: SelectorProvider<Project, { $ref: string }>;
  projectFilter = input<ProjectFilter>({ limit: 100 });
  typeProvider: SelectorProvider<Type, { $ref: string }>;
  typeFilter = input<TypeFilter>({ limit: 100 });
  configTemplateProvider: SelectorProvider<ConfigTemplate, { $ref: string }>;
  configTemplateFilter = input<ConfigTemplateFilter>({ limit: 100 });
  floorsProvider: SelectorProvider<Floor, { $ref: string }>;
  floorsFilter = input<FloorFilter>({ limit: 100 });
  modelProvider: SelectorProvider<Model, { $ref: string }>;
  modelFilter = input<ModelFilter>({ limit: 100 });
  configTemplatesProvider: SelectorProvider<ConfigTemplate, { $ref: string }>;
  configTemplatesFilter = input<ConfigTemplateFilter>({ limit: 100 });
  floorProvider: SelectorProvider<Floor, { $ref: string }>;
  floorFilter = input<FloorFilter>({ limit: 100 });
  public constructor(
    projectDeviceRepository: ProjectDeviceRepository,
    modelRepository: ModelRepository,
    typeRepository: TypeRepository,
    projectRepository: ProjectRepository,
    configTemplateRepository: ConfigTemplateRepository,
    floorRepository: FloorRepository,
  ) {
    super(
      new FormGroup({
        models: new FormControl<any>(null),
        types: new FormControl<any>(null),
        projects: new FormControl<any>(null),
        project: new FormControl<any>(null),
        type: new FormControl<any>(null),
        configTemplate: new FormControl<any>(null),
        search: new FormControl<string>(''),
        floors: new FormControl<any>(null),
        name: new FormControl<string>(''),
        model: new FormControl<any>(null),
        configTemplates: new FormControl<any>(null),
        floor: new FormControl<any>(null),
        order: new FormControl<string>(''),
      }),
    );
    this.acl = projectDeviceRepository.acl();
    effect(() => {
      this.acl.fetch(this.uid() || null);
    });
    effect(() => {
      const vals = this.acl();
      const value = this.value();
      const on = this.uid() ? vals?.specific : vals?.generic;
      setTimeout(() => {
        this.definedFixed.set(on?.fields?.noEditables || []);
        this.definedHidden.set(on?.fields?.noVisibles || []);
      });
    });
    this.modelsProvider = modelRepository.selectorProvider(this.modelsFilter);
    this.typesProvider = typeRepository.selectorProvider(this.typesFilter);
    this.projectsProvider = projectRepository.selectorProvider(this.projectsFilter);
    this.projectProvider = projectRepository.selectorProvider(this.projectFilter);
    this.typeProvider = typeRepository.selectorProvider(this.typeFilter);
    this.configTemplateProvider = configTemplateRepository.selectorProvider(this.configTemplateFilter);
    this.floorsProvider = floorRepository.selectorProvider(this.floorsFilter);
    this.modelProvider = modelRepository.selectorProvider(this.modelFilter);
    this.configTemplatesProvider = configTemplateRepository.selectorProvider(this.configTemplatesFilter);
    this.floorProvider = floorRepository.selectorProvider(this.floorFilter);
    this.defaultValues = () => {
      return {
        models: null,
        types: null,
        projects: null,
        project: null,
        type: null,
        configTemplate: null,
        search: '',
        floors: null,
        name: '',
        model: null,
        configTemplates: null,
        floor: null,
        order: '',
      };
    };
  }
}
