/* @autogenerated */
import { EditableTextComponent } from 'app/common/toolkit/editable/editable-text/editable-text.component';
import { EditableChooseComponent } from 'app/common/toolkit/editable/editable-choose/editable-choose.component';
import { MatInputModule } from '@angular/material/input';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { FormLayoutComponent } from 'app/common/toolkit/form-layout/form-layout.component';
import { ConfigTemplateViewSearchComponent } from './config-template-view-search.component';
import { provideTranslocoScope } from '@jsverse/transloco';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [ConfigTemplateViewSearchComponent],
  exports: [ConfigTemplateViewSearchComponent],
  imports: [
    CommonModule,
    EditableChooseComponent,
    EditableTextComponent,
    FormLayoutComponent,
    FormsModule,
    MatInputModule,
    ReactiveFormsModule,
  ],
  providers: [
    provideTranslocoScope({ scope: 'infrastructure/config-template', alias: 'infrastructure.config-template' }),
  ],
  bootstrap: [],
})
export class ConfigTemplateViewSearchModule {}
