/* @autogenerated */
import { TranslocoModule, provideTranslocoScope } from '@jsverse/transloco';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { TypeViewFormGroupModule } from 'app/features/infrastructure/type/components/type-view-form-group/type-view-form-group.module';
import { TypeViewEditActionComponent } from './type-view-edit-action.component';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [TypeViewEditActionComponent],
  exports: [TypeViewEditActionComponent],
  imports: [CommonModule, MatButtonModule, ReactiveFormsModule, TranslocoModule, TypeViewFormGroupModule],
  providers: [provideTranslocoScope({ scope: 'infrastructure/type', alias: 'infrastructure.type' })],
  bootstrap: [],
})
export class TypeViewEditActionModule {}
