/* @autogenerated */
import { Component } from '@angular/core';

@Component({
  selector: 'client-view-list-page',
  template: '<client-view-list />',
  standalone: false,
  styles: [
    ':host { flex: 1; display: flex; flex-direction: column; overflow: hidden;  border-radius: var(--mat-sys-corner-medium); box-shadow: var(--mat-sys-level3); margin: 15px; }',
  ],
})
export class ClientViewListPageComponent {}
