/* @autogenerated */
import { Component } from '@angular/core';

@Component({
  selector: 'client-view-list-page',
  template: '<client-view-list />',
  standalone: false,
  styles: [':host { flex: 1; display: flex; flex-direction: column; overflow: hidden; margin: 15px; }'],
})
export class ClientViewListPageComponent {}
