/* @autogenerated */

export interface Client {
  uid: string;
  name: string;
  enabled: boolean;
  version?: number;
}
export interface ClientFilter {
  search?: string;
  uids?: string[];
  limit?: number;
  order?: string;
  name?: string;
}
export interface ClientProjection {
  uid: string;
  name: string;
  enabled: boolean;
  version?: number;
}
export function clientProjectionToValue(proyection: Client | ClientProjection | null | undefined): Client | null {
  return proyection
    ? {
        uid: proyection.uid,
        name: proyection.name,
        enabled: proyection.enabled,
        version: proyection.version,
      }
    : null;
}
