/* @autogenerated */
import { DeviceCheckViewFormGroupModule } from 'app/features/installations/device-check/components/device-check-view-form-group/device-check-view-form-group.module';
import { ReactiveFormsModule } from '@angular/forms';
import { DeviceCheckViewDetailComponent } from './device-check-view-detail.component';
import { provideTranslocoScope } from '@jsverse/transloco';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [DeviceCheckViewDetailComponent],
  exports: [DeviceCheckViewDetailComponent],
  imports: [DeviceCheckViewFormGroupModule, ReactiveFormsModule],
  providers: [provideTranslocoScope({ scope: 'installations/device-check', alias: 'installations.device-check' })],
  bootstrap: [],
})
export class DeviceCheckViewDetailModule {}
