/* @autogenerated */
import { TranslocoModule, provideTranslocoScope } from '@jsverse/transloco';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { ClientViewFormGroupModule } from 'app/features/organization/client/components/client-view-form-group/client-view-form-group.module';
import { ClientViewEditActionComponent } from './client-view-edit-action.component';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [ClientViewEditActionComponent],
  exports: [ClientViewEditActionComponent],
  imports: [ClientViewFormGroupModule, CommonModule, MatButtonModule, ReactiveFormsModule, TranslocoModule],
  providers: [provideTranslocoScope({ scope: 'organization/client', alias: 'organization.client' })],
  bootstrap: [],
})
export class ClientViewEditActionModule {}
