/* @autogenerated */
export interface LongTask {
  uid: string;
  status: 'PENDING' | 'PROCESSING' | 'FINISHED' | 'FAILED';
  startTime?: Date;
  endTime?: Date;
  steps: LongTaskStep[];
}

export interface LongTaskStep {
  name: string;
  status: 'PENDING' | 'PROCESSING' | 'FINISHED' | 'FAILED';
  startTime?: Date;
  endTime?: Date;
  totalItems: number;
  processedItems: number;
  oks: string[];
  warns: { item: string; fails: string[] }[];
  errors: { item: string; fails: string[] }[];
}
