/* @autogenerated */

export interface ConfigTemplate {
  uid: string;
  name: string;
  version?: number;
}
export interface ConfigTemplateFilter {
  search?: string;
  uids?: string[];
  limit?: number;
  order?: string;
  name?: string;
}
export interface ConfigTemplateProjection {
  uid: string;
  name: string;
  version?: number;
}
export function configTemplateProjectionToValue(
  proyection: ConfigTemplate | ConfigTemplateProjection | null | undefined,
): ConfigTemplate | null {
  return proyection
    ? {
        uid: proyection.uid,
        name: proyection.name,
        version: proyection.version,
      }
    : null;
}
