/* @autogenerated */
import { Component } from '@angular/core';

@Component({
  selector: 'app-bootstrap',
  standalone: true,
  template: '<h1>Loading...</h1>',
})
export class BootstrapComponent {}
