/* @autogenerated */
import { MatDialogModule } from '@angular/material/dialog';
import { MatSnackBarModule } from '@angular/material/snack-bar';
import { TranslocoModule, provideTranslocoScope } from '@jsverse/transloco';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { DeviceInstanceViewFormGroupModule } from 'app/features/installations/device-instance/components/device-instance-view-form-group/device-instance-view-form-group.module';
import { DeviceInstanceViewDeleteActionComponent } from './device-instance-view-delete-action.component';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [DeviceInstanceViewDeleteActionComponent],
  exports: [DeviceInstanceViewDeleteActionComponent],
  imports: [
    CommonModule,
    DeviceInstanceViewFormGroupModule,
    MatButtonModule,
    MatDialogModule,
    MatSnackBarModule,
    ReactiveFormsModule,
    TranslocoModule,
  ],
  providers: [
    provideTranslocoScope({ scope: 'installations/device-instance', alias: 'installations.device-instance' }),
  ],
  bootstrap: [],
})
export class DeviceInstanceViewDeleteActionModule {}
