/* @autogenerated */
import { TranslocoService } from '@jsverse/transloco';
import { DeviceInstanceRepository } from 'app/features/installations/device-instance/repository/device-instance-repository.service';
import { ActionContainerComponent } from 'app/common/toolkit/action/action-container.component';
import { Action } from 'app/common/toolkit/action/action.model';
import { Tick } from 'app/common/data/repository/repository.model';
import { Acl } from 'app/common/data/acl/acl.model';
import { Subscription } from 'rxjs';
import { MatSnackBar } from '@angular/material/snack-bar';
import { MatDialog, MatDialogRef } from '@angular/material/dialog';
import { DeviceInstance } from 'app/features/installations/device-instance/model/device-instance.model';
import { OnDestroy, input, viewChild, Component, signal, TemplateRef } from '@angular/core';

@Component({
  selector: 'device-instance-view-delete-action',
  standalone: false,
  templateUrl: './device-instance-view-delete-action.component.html',
  styleUrl: './device-instance-view-delete-action.component.scss',
})
export class DeviceInstanceViewDeleteActionComponent implements Action, OnDestroy {
  readonly name = 'delete';
  readonly contextual = true;
  readonly multiple = false;
  container = signal<ActionContainerComponent | undefined>(undefined);
  selection = signal<any[]>([]);
  render = signal<TemplateRef<any> | undefined>(undefined);
  dialogTemplate = viewChild<TemplateRef<any>>('dialogTemplate');

  title = signal<string>('Borrando el item');
  label = signal<string>('Delete');
  icon = signal<string>('delete');
  tooltip = signal<string>('Borra el elemento seleccionado');
  default = input<boolean>(false);

  visibleValue = signal(false);
  enabledValue = signal(true);

  acl: Tick<{ generic: Acl; specific: Acl }, string | null>;

  private dialgoRef?: MatDialogRef<any, any>;
  private dialogSubs?: Subscription;
  private dismiss = 'Close';
  private report = 'Deleted...';

  constructor(
    private readonly repository: DeviceInstanceRepository,
    private readonly dialog: MatDialog,
    private readonly snakeBar: MatSnackBar,
    transloco: TranslocoService,
  ) {
    this.acl = repository.acl();
    this.acl.fetch(null).subscribe((info) => {
      this.visibleValue.set(this.allowed(info?.generic));
    });
    transloco.selectTranslateObject('action.delete', {}, 'installations/device-instance').subscribe((val) => {
      if (val.label) {
        this.label.set(val.label);
      }
      if (val.tooltip) {
        this.tooltip.set(val.tooltip);
      }
      if (val.icon) {
        this.icon.set(val.icon);
      }
      if (val.title) {
        this.title.set(val.title);
      }
      if (val.dismiss) {
        this.dismiss = val.dismiss;
      }
      if (val.report) {
        this.report = val.report;
      }
    });
  }

  visible(items: any[]) {
    return this.visibleValue;
  }

  enabled(items: any[]) {
    return this.enabledValue;
  }
  run(): void {
    const template = this.dialogTemplate();
    if (template) {
      this.dialgoRef?.close();
      this.dialgoRef = this.dialog.open(template);
      this.dialogSubs = this.dialgoRef.afterClosed().subscribe((val) => {
        if (val) {
          this.delete(this.selection()[0] as DeviceInstance);
        } else {
          this.container()?.close();
        }
      });
    }
  }

  ngOnDestroy(): void {
    this.dialgoRef?.close();
    this.dialogSubs?.unsubscribe();
  }

  private delete(item: DeviceInstance) {
    this.repository.deleteByKey(item.uid).subscribe(() => {
      this.container()?.close();
      this.snakeBar.open(this.report, this.dismiss, { duration: 5000 });
    });
  }
  private allowed(allow: Acl | undefined) {
    return !!allow?.allows?.find((info) => info.name == 'delete')?.allowed;
  }
}
