/* @autogenerated */

export interface Type {
  uid: string;
  name: string;
  version?: number;
}
export interface TypeFilter {
  search?: string;
  uids?: string[];
  limit?: number;
  order?: string;
  name?: string;
}
export interface TypeProjection {
  uid: string;
  name: string;
  version?: number;
}
export function typeProjectionToValue(proyection: Type | TypeProjection | null | undefined): Type | null {
  return proyection
    ? {
        uid: proyection.uid,
        name: proyection.name,
        version: proyection.version,
      }
    : null;
}
