/* @autogenerated */
import { ClientRepository } from '@features/organization/client/repository/client-repository.service';
import { DisplayProvider } from '@common/data/display-provider';
import { ApiProvider } from '@common/data/repository/provider/impl/api.provider';
import { ApiService } from '@common/data/api/api.service';
import { selectorProvider, SelectorProvider } from '@common/data/selector-provider';
import { Acl } from '@common/data/acl/acl.model';
import { Observable, of } from 'rxjs';
import { RepositoryMetadata, RepositoryService } from '@common/data/repository/repository.service';
import { Site, SiteProjection, SiteFilter } from '@features/organization/site/model/site.model';
import { Shift, Tick } from '@common/data/repository/repository.model';
import { Injectable, Signal } from '@angular/core';
import { Slide } from '@common/data/repository/provider/repository-provider.interface';

@Injectable({ providedIn: 'root' })
export class SiteRepository {
  private readonly repo: RepositoryService<Site, SiteFilter>;
  public static metadata(api: ApiService): RepositoryMetadata<Site, SiteFilter> {
    return {
      key: 'uid',
      name: 'site',
      provider: new ApiProvider(
        'uid',
        api,
        'http://net-civeira-netconfighub/organization/sites',
        'http://net-civeira-netconfighub/me/acl/organization/sites',
      ),
      reference: (name: string): RepositoryService<any, any> | null => {
        if ('client' == name) {
          return new RepositoryService(ClientRepository.metadata(api));
        }
        return null;
      },
    };
  }
  constructor(api: ApiService) {
    this.repo = new RepositoryService(SiteRepository.metadata(api));
  }
  acl(): Tick<{ generic: Acl; specific: Acl }, string | null> {
    return this.repo.acl();
  }
  checkAcl(key?: string): Observable<Acl> {
    return this.repo.checkAcl(key || null);
  }
  generateComb(): string {
    return this.repo.generateComb();
  }

  add(item: Site): Observable<Site> {
    item['uid'] = this.generateComb();
    return this.repo.add(item);
  }
  update(item: Site): Observable<Site> {
    return this.repo.update(item);
  }
  deleteByKey(item: string): Observable<void> {
    return this.repo.deleteByKey(item);
  }
  canDeleteSelection(): boolean {
    return this.repo.canDeleteSelection();
  }
  deleteSelection(filter: SiteFilter): Observable<any> {
    return this.repo.deleteSelection(this.publicQueryFilter(filter));
  }
  retrieve(code: string): Observable<Site | undefined> {
    return this.repo.retrieve(code);
  }
  projection(includes: string[]): Tick<SiteProjection, string> {
    return this.repo.projection(includes);
  }
  list(filter: SiteFilter): Observable<Slide<Site>> {
    return this.repo.list(this.publicQueryFilter(filter));
  }
  values(filter: SiteFilter): Observable<Site[]> {
    return this.repo.values(this.publicQueryFilter(filter));
  }
  projections(includes: string[]): Shift<SiteProjection[], SiteFilter> {
    return this.repo.projections(includes);
  }
  displayProvider(): DisplayProvider<Site> {
    return {
      display: (item: Site) => {
        return item.name!;
      },
    };
  }
  selectorProvider(filter?: Signal<SiteFilter>): SelectorProvider<Site, { $ref: string }> {
    return selectorProvider({
      search: (text: string) => {
        const filterValue = filter ? filter() : { limit: 10 };
        filterValue.search = text;
        return this.values(filterValue);
      },
      display: (item: Site) => {
        return item.name!;
      },
      value: (item: Site) => {
        return { $ref: item.uid! };
      },
      select: (ref: { $ref: string }) => {
        return ref['$ref'] ? this.retrieve(ref['$ref']) : of(undefined);
      },
      equals: (one: { $ref: string }, other: { $ref: string }) => {
        return one.$ref === other.$ref;
      },
    });
  }
  private publicQueryFilter(filter: SiteFilter): SiteFilter {
    const morphed = {} as any;
    if (filter.search) {
      morphed['search'] = filter.search;
    }
    if (filter.uids) {
      morphed['uids'] = filter.uids.join(',');
    }
    if (filter.limit) {
      morphed['limit'] = filter.limit;
    }
    if (filter.order) {
      morphed['order'] = filter.order;
    }
    if (filter.name) {
      morphed['name'] = filter.name;
    }
    if (filter.client) {
      morphed['client'] = filter.client;
    }
    if (filter.clients) {
      morphed['clients'] = filter.clients;
    }
    return morphed;
  }
}
