/* @autogenerated */
import { FloorViewFormGroupModule } from 'app/features/organization/floor/components/floor-view-form-group/floor-view-form-group.module';
import { ReactiveFormsModule } from '@angular/forms';
import { FloorViewDetailComponent } from './floor-view-detail.component';
import { provideTranslocoScope } from '@jsverse/transloco';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [FloorViewDetailComponent],
  exports: [FloorViewDetailComponent],
  imports: [FloorViewFormGroupModule, ReactiveFormsModule],
  providers: [provideTranslocoScope({ scope: 'organization/floor', alias: 'organization.floor' })],
  bootstrap: [],
})
export class FloorViewDetailModule {}
