/* @autogenerated */
import { FormControl } from '@angular/forms';
import { input, effect, Component } from '@angular/core';
import { Floor } from 'app/features/organization/floor/model/floor.model';

@Component({
  selector: 'floor-view-detail',
  templateUrl: './floor-view-detail.component.html',
  styleUrl: './floor-view-detail.component.scss',
  standalone: false,
})
export class FloorViewDetailComponent {
  data = input.required<Floor | null>();
  form = new FormControl<Floor | undefined>({ value: undefined, disabled: true });

  public constructor() {
    effect(() => this.form.patchValue(this.data()));
  }
}
