/* @autogenerated */
import { ActionContainerComponent } from 'app/common/toolkit/action/action-container.component';
import { TypeViewCreateActionModule } from 'app/features/infrastructure/type/actions/type-view-create-action/type-view-create-action.module';
import { TypeViewEditActionModule } from 'app/features/infrastructure/type/actions/type-view-edit-action/type-view-edit-action.module';
import { TypeViewDetailActionModule } from 'app/features/infrastructure/type/actions/type-view-detail-action/type-view-detail-action.module';
import { TypeViewDeleteActionModule } from 'app/features/infrastructure/type/actions/type-view-delete-action/type-view-delete-action.module';
import { TypeViewDeleteSelectionActionModule } from 'app/features/infrastructure/type/actions/type-view-delete-selection-action/type-view-delete-selection-action.module';
import { TypeViewStandarActionsComponent } from './type-view-standar-actions.component';
import { provideTranslocoScope } from '@jsverse/transloco';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [TypeViewStandarActionsComponent],
  exports: [TypeViewStandarActionsComponent],
  imports: [
    ActionContainerComponent,
    TypeViewCreateActionModule,
    TypeViewDeleteActionModule,
    TypeViewDeleteSelectionActionModule,
    TypeViewDetailActionModule,
    TypeViewEditActionModule,
  ],
  providers: [provideTranslocoScope({ scope: 'infrastructure/type', alias: 'infrastructure.type' })],
  bootstrap: [],
})
export class TypeViewStandarActionsModule {}
