/* @autogenerated */
import { TranslocoModule, provideTranslocoScope } from '@jsverse/transloco';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { FloorViewDetailModule } from 'app/features/organization/floor/components/floor-view-detail/floor-view-detail.module';
import { FloorViewDetailActionComponent } from './floor-view-detail-action.component';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [FloorViewDetailActionComponent],
  exports: [FloorViewDetailActionComponent],
  imports: [CommonModule, FloorViewDetailModule, MatButtonModule, ReactiveFormsModule, TranslocoModule],
  providers: [provideTranslocoScope({ scope: 'organization/floor', alias: 'organization.floor' })],
  bootstrap: [],
})
export class FloorViewDetailActionModule {}
