/* @autogenerated */
import { MatDialogModule } from '@angular/material/dialog';
import { MatSnackBarModule } from '@angular/material/snack-bar';
import { TranslocoModule, provideTranslocoScope } from '@jsverse/transloco';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { TypeViewFormGroupModule } from 'app/features/infrastructure/type/components/type-view-form-group/type-view-form-group.module';
import { TypeViewDeleteSelectionActionComponent } from './type-view-delete-selection-action.component';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [TypeViewDeleteSelectionActionComponent],
  exports: [TypeViewDeleteSelectionActionComponent],
  imports: [
    CommonModule,
    MatButtonModule,
    MatDialogModule,
    MatSnackBarModule,
    ReactiveFormsModule,
    TranslocoModule,
    TypeViewFormGroupModule,
  ],
  providers: [provideTranslocoScope({ scope: 'infrastructure/type', alias: 'infrastructure.type' })],
  bootstrap: [],
})
export class TypeViewDeleteSelectionActionModule {}
