/* @autogenerated */
import { EditableTextComponent } from 'app/common/toolkit/editable/editable-text/editable-text.component';
import { MatInputModule } from '@angular/material/input';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { FormLayoutComponent } from 'app/common/toolkit/form-layout/form-layout.component';
import { TypeViewFormGroupComponent } from './type-view-form-group.component';
import { provideTranslocoScope } from '@jsverse/transloco';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [TypeViewFormGroupComponent],
  exports: [TypeViewFormGroupComponent],
  imports: [CommonModule, EditableTextComponent, FormLayoutComponent, FormsModule, MatInputModule, ReactiveFormsModule],
  providers: [provideTranslocoScope({ scope: 'infrastructure/type', alias: 'infrastructure.type' })],
  bootstrap: [],
})
export class TypeViewFormGroupModule {}
