/* @autogenerated */
import { ActionContainerComponent } from 'app/common/toolkit/action/action-container.component';
import { SiteViewCreateActionModule } from 'app/features/organization/site/actions/site-view-create-action/site-view-create-action.module';
import { SiteViewEditActionModule } from 'app/features/organization/site/actions/site-view-edit-action/site-view-edit-action.module';
import { SiteViewDetailActionModule } from 'app/features/organization/site/actions/site-view-detail-action/site-view-detail-action.module';
import { SiteViewDeleteActionModule } from 'app/features/organization/site/actions/site-view-delete-action/site-view-delete-action.module';
import { SiteViewDeleteSelectionActionModule } from 'app/features/organization/site/actions/site-view-delete-selection-action/site-view-delete-selection-action.module';
import { SiteViewFloorsModule } from 'app/features/organization/site/actions/site-view-floors/site-view-floors.module';
import { SiteViewStandarActionsComponent } from './site-view-standar-actions.component';
import { provideTranslocoScope } from '@jsverse/transloco';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [SiteViewStandarActionsComponent],
  exports: [SiteViewStandarActionsComponent],
  imports: [
    ActionContainerComponent,
    SiteViewCreateActionModule,
    SiteViewDeleteActionModule,
    SiteViewDeleteSelectionActionModule,
    SiteViewDetailActionModule,
    SiteViewEditActionModule,
    SiteViewFloorsModule,
  ],
  providers: [provideTranslocoScope({ scope: 'organization/site', alias: 'organization.site' })],
  bootstrap: [],
})
export class SiteViewStandarActionsModule {}
