/* @autogenerated */
import {
  DeviceCheckProjection,
  DeviceCheckFilter,
} from 'app/features/installations/device-check/model/device-check.model';
import { DisplayProvider } from '@common/data/display-provider';
import { DeviceCheckRepository } from 'app/features/installations/device-check/repository/device-check-repository.service';
import { FormControl } from '@angular/forms';
import { Shift } from '@common/data/repository/repository.model';
import { input, effect, Component } from '@angular/core';

@Component({
  selector: 'device-check-view-list',
  templateUrl: './device-check-view-list.component.html',
  styleUrls: ['./device-check-view-list.component.scss'],
  standalone: false,
})
export class DeviceCheckViewListComponent {
  filters = input<DeviceCheckFilter>();
  actionName = input<string>('device-check');
  fixed = input<{ [key: string]: any }>();
  hidden = input<{ [key: string]: any }>();
  search = new FormControl<any>(undefined);
  list: Shift<DeviceCheckProjection[], DeviceCheckFilter>;
  displayer: DisplayProvider<any>;

  constructor(repository: DeviceCheckRepository) {
    this.displayer = repository.displayProvider();
    this.list = repository.projections(['projectDevice']);
    effect(() => {
      setTimeout(() => this.makeSearch());
    });
  }
  makeSearch() {
    const result = { limit: 10 } as any;
    const filter = this.search.value;
    const external = this.filters();
    if (external?.search) {
      result.search = external.search;
    }
    if (external?.result) {
      result.result = external.result;
    }
    if (external?.projectDevice) {
      result.projectDevice = external.projectDevice;
    }
    if (external?.projectDevices) {
      result.projectDevices = external.projectDevices;
    }
    if (filter?.search) {
      result.search = filter.search;
    }
    if (filter?.result) {
      result.result = filter.result;
    }
    if (filter?.projectDevice?.$ref) {
      result.projectDevice = filter.projectDevice.$ref;
    }
    if (filter?.projectDevices?.$ref) {
      result.projectDevices = filter.projectDevices.$ref;
    }
    if (filter?.order) {
      result.order = filter.order;
    }
    this.list.fetch(result);
  }

  next() {
    this.list.next();
  }

  reload() {
    this.list.reset();
  }

  prev() {
    console.log('PREV');
  }
}
