/* @autogenerated */
import { TranslocoModule, provideTranslocoScope } from '@jsverse/transloco';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { DeviceInstanceViewFormGroupModule } from 'app/features/installations/device-instance/components/device-instance-view-form-group/device-instance-view-form-group.module';
import { DeviceInstanceViewEditActionComponent } from './device-instance-view-edit-action.component';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [DeviceInstanceViewEditActionComponent],
  exports: [DeviceInstanceViewEditActionComponent],
  imports: [CommonModule, DeviceInstanceViewFormGroupModule, MatButtonModule, ReactiveFormsModule, TranslocoModule],
  providers: [
    provideTranslocoScope({ scope: 'installations/device-instance', alias: 'installations.device-instance' }),
  ],
  bootstrap: [],
})
export class DeviceInstanceViewEditActionModule {}
