/* @autogenerated */
import { EditableSelectoneComponent } from 'app/common/toolkit/editable/editable-selectone/editable-selectone.component';
import { EditableTextComponent } from 'app/common/toolkit/editable/editable-text/editable-text.component';
import { EditableChooseComponent } from 'app/common/toolkit/editable/editable-choose/editable-choose.component';
import { MatInputModule } from '@angular/material/input';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { FormLayoutComponent } from 'app/common/toolkit/form-layout/form-layout.component';
import { DeviceInstanceViewSearchComponent } from './device-instance-view-search.component';
import { provideTranslocoScope } from '@jsverse/transloco';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [DeviceInstanceViewSearchComponent],
  exports: [DeviceInstanceViewSearchComponent],
  imports: [
    CommonModule,
    EditableChooseComponent,
    EditableSelectoneComponent,
    EditableTextComponent,
    FormLayoutComponent,
    FormsModule,
    MatInputModule,
    ReactiveFormsModule,
  ],
  providers: [
    provideTranslocoScope({ scope: 'installations/device-instance', alias: 'installations.device-instance' }),
  ],
  bootstrap: [],
})
export class DeviceInstanceViewSearchModule {}
