/* @autogenerated */
import { ActionContainerComponent } from 'app/common/toolkit/action/action-container.component';
import { ClientViewCreateActionModule } from 'app/features/organization/client/actions/client-view-create-action/client-view-create-action.module';
import { ClientViewEditActionModule } from 'app/features/organization/client/actions/client-view-edit-action/client-view-edit-action.module';
import { ClientViewDetailActionModule } from 'app/features/organization/client/actions/client-view-detail-action/client-view-detail-action.module';
import { ClientViewDeleteActionModule } from 'app/features/organization/client/actions/client-view-delete-action/client-view-delete-action.module';
import { ClientViewDeleteSelectionActionModule } from 'app/features/organization/client/actions/client-view-delete-selection-action/client-view-delete-selection-action.module';
import { ClientViewEnableActionModule } from 'app/features/organization/client/actions/client-view-enable-action/client-view-enable-action.module';
import { ClientViewEnableSelectionActionModule } from 'app/features/organization/client/actions/client-view-enable-selection-action/client-view-enable-selection-action.module';
import { ClientViewDisableActionModule } from 'app/features/organization/client/actions/client-view-disable-action/client-view-disable-action.module';
import { ClientViewDisableSelectionActionModule } from 'app/features/organization/client/actions/client-view-disable-selection-action/client-view-disable-selection-action.module';
import { ClientViewSitesModule } from 'app/features/organization/client/actions/client-view-sites/client-view-sites.module';
import { ClientViewStandarActionsComponent } from './client-view-standar-actions.component';
import { provideTranslocoScope } from '@jsverse/transloco';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [ClientViewStandarActionsComponent],
  exports: [ClientViewStandarActionsComponent],
  imports: [
    ActionContainerComponent,
    ClientViewCreateActionModule,
    ClientViewDeleteActionModule,
    ClientViewDeleteSelectionActionModule,
    ClientViewDetailActionModule,
    ClientViewDisableActionModule,
    ClientViewDisableSelectionActionModule,
    ClientViewEditActionModule,
    ClientViewEnableActionModule,
    ClientViewEnableSelectionActionModule,
    ClientViewSitesModule,
  ],
  providers: [provideTranslocoScope({ scope: 'organization/client', alias: 'organization.client' })],
  bootstrap: [],
})
export class ClientViewStandarActionsModule {}
