/* @autogenerated */
import { TypeRepository } from 'app/features/infrastructure/type/repository/type-repository.service';
import { FormControl } from '@angular/forms';
import { Shift } from '@common/data/repository/repository.model';
import { input, effect, Component } from '@angular/core';
import { TypeProjection, TypeFilter } from 'app/features/infrastructure/type/model/type.model';

@Component({
  selector: 'type-view-list',
  templateUrl: './type-view-list.component.html',
  styleUrls: ['./type-view-list.component.scss'],
  standalone: false,
})
export class TypeViewListComponent {
  filters = input<TypeFilter>();
  actionName = input<string>('type');
  fixed = input<{ [key: string]: any }>();
  hidden = input<{ [key: string]: any }>();
  search = new FormControl<any>(undefined);
  list: Shift<TypeProjection[], TypeFilter>;

  constructor(repository: TypeRepository) {
    this.list = repository.projections([]);
    effect(() => {
      setTimeout(() => this.makeSearch());
    });
  }
  makeSearch() {
    const result = { limit: 10 } as any;
    const filter = this.search.value;
    const external = this.filters();
    if (external?.search) {
      result.search = external.search;
    }
    if (external?.name) {
      result.name = external.name;
    }
    if (filter?.search) {
      result.search = filter.search;
    }
    if (filter?.name) {
      result.name = filter.name;
    }
    if (filter?.order) {
      result.order = filter.order;
    }
    this.list.fetch(result);
  }

  next() {
    this.list.next();
  }

  reload() {
    this.list.reset();
  }

  prev() {
    console.log('PREV');
  }
}
