/* @autogenerated */
import { ActionContainerComponent } from 'app/common/toolkit/action/action-container.component';
import { ProjectViewCreateActionModule } from 'app/features/installations/project/actions/project-view-create-action/project-view-create-action.module';
import { ProjectViewEditActionModule } from 'app/features/installations/project/actions/project-view-edit-action/project-view-edit-action.module';
import { ProjectViewDetailActionModule } from 'app/features/installations/project/actions/project-view-detail-action/project-view-detail-action.module';
import { ProjectViewDeleteActionModule } from 'app/features/installations/project/actions/project-view-delete-action/project-view-delete-action.module';
import { ProjectViewDeleteSelectionActionModule } from 'app/features/installations/project/actions/project-view-delete-selection-action/project-view-delete-selection-action.module';
import { ProjectViewStandarActionsComponent } from './project-view-standar-actions.component';
import { provideTranslocoScope } from '@jsverse/transloco';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [ProjectViewStandarActionsComponent],
  exports: [ProjectViewStandarActionsComponent],
  imports: [
    ActionContainerComponent,
    ProjectViewCreateActionModule,
    ProjectViewDeleteActionModule,
    ProjectViewDeleteSelectionActionModule,
    ProjectViewDetailActionModule,
    ProjectViewEditActionModule,
  ],
  providers: [provideTranslocoScope({ scope: 'installations/project', alias: 'installations.project' })],
  bootstrap: [],
})
export class ProjectViewStandarActionsModule {}
