/* @autogenerated */
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { DeviceCheckViewListPageComponent } from './device-check-view-list-page.component';
import { DeviceCheckViewListModule } from '@features/installations/device-check/components/device-check-view-list/device-check-view-list.module';

const routes: Routes = [{ path: '', component: DeviceCheckViewListPageComponent }];
@NgModule({
  declarations: [DeviceCheckViewListPageComponent],
  imports: [RouterModule.forChild(routes), DeviceCheckViewListModule],
  exports: [RouterModule],
})
export class DeviceCheckViewListRouteModule {}
