/* @autogenerated */
import { Component } from '@angular/core';

@Component({
  selector: 'device-check-view-list-page',
  template: '<device-check-view-list />',
  standalone: false,
  styles: [':host { flex: 1; display: flex; flex-direction: column; overflow: hidden; margin: 15px; }'],
})
export class DeviceCheckViewListPageComponent {}
