/* @autogenerated */
import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-page-error',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './error-page.component.html',
  styleUrls: ['./error-page.component.css'],
})
export class ErrorPageComponent {
  @Input() error: any;
  @Input() asColumn = false;
  smallScreen = false;

  constructor() {}

  public responseMessage() {
    if (this.error.error) {
      if (this.error.error.message) {
        return this.error.error.message;
      } else if (typeof this.error.error === 'string') {
        return this.error.error;
      } else {
        return JSON.stringify(this.error.error);
      }
    } else {
      return 'No message';
    }
  }

  public prefix() {
    if (this.error.error && this.error.error[0]) {
      if ('not-empty' === this.error.error[0].description) {
        return 'no_empty_';
      }
    }
    return '';
  }

  public sufix() {
    if (this.error.error && this.error.error[0]) {
      if ('not-empty' === this.error.error[0].description) {
        return '-no-empty';
      }
    }
    return '';
  }

  public isUnknown() {
    // console.error(this.error);
    if (!this.error) {
      return true;
    }
    if (null == this.error.status) {
      return false;
    }
    const unknown = [0, 401, 402, 403, 404, 409, 422];
    for (const u of unknown) {
      if (this.error.status === u) {
        return false;
      }
    }
    return true;
  }
}
