/* @autogenerated */
import { MatDialogModule } from '@angular/material/dialog';
import { MatSnackBarModule } from '@angular/material/snack-bar';
import { TranslocoModule, provideTranslocoScope } from '@jsverse/transloco';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { ClientViewFormGroupModule } from 'app/features/organization/client/components/client-view-form-group/client-view-form-group.module';
import { ClientViewEnableActionComponent } from './client-view-enable-action.component';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [ClientViewEnableActionComponent],
  exports: [ClientViewEnableActionComponent],
  imports: [
    ClientViewFormGroupModule,
    CommonModule,
    MatButtonModule,
    MatDialogModule,
    MatSnackBarModule,
    ReactiveFormsModule,
    TranslocoModule,
  ],
  providers: [provideTranslocoScope({ scope: 'organization/client', alias: 'organization.client' })],
  bootstrap: [],
})
export class ClientViewEnableActionModule {}
