/* @autogenerated */
import { FormControl } from '@angular/forms';
import { input, effect, Component } from '@angular/core';
import { Type } from 'app/features/infrastructure/type/model/type.model';

@Component({
  selector: 'type-view-detail',
  templateUrl: './type-view-detail.component.html',
  styleUrl: './type-view-detail.component.scss',
  standalone: false,
})
export class TypeViewDetailComponent {
  data = input.required<Type | null>();
  form = new FormControl<Type | undefined>({ value: undefined, disabled: true });

  public constructor() {
    effect(() => this.form.patchValue(this.data()));
  }
}
