/* @autogenerated */
import { TypeViewFormGroupModule } from 'app/features/infrastructure/type/components/type-view-form-group/type-view-form-group.module';
import { ReactiveFormsModule } from '@angular/forms';
import { TypeViewDetailComponent } from './type-view-detail.component';
import { provideTranslocoScope } from '@jsverse/transloco';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [TypeViewDetailComponent],
  exports: [TypeViewDetailComponent],
  imports: [ReactiveFormsModule, TypeViewFormGroupModule],
  providers: [provideTranslocoScope({ scope: 'infrastructure/type', alias: 'infrastructure.type' })],
  bootstrap: [],
})
export class TypeViewDetailModule {}
