/* @autogenerated */
import { TranslocoModule, provideTranslocoScope } from '@jsverse/transloco';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { SiteViewDetailModule } from 'app/features/organization/site/components/site-view-detail/site-view-detail.module';
import { SiteViewDetailActionComponent } from './site-view-detail-action.component';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [SiteViewDetailActionComponent],
  exports: [SiteViewDetailActionComponent],
  imports: [CommonModule, MatButtonModule, ReactiveFormsModule, SiteViewDetailModule, TranslocoModule],
  providers: [provideTranslocoScope({ scope: 'organization/site', alias: 'organization.site' })],
  bootstrap: [],
})
export class SiteViewDetailActionModule {}
