/* @autogenerated */
import { TranslocoModule, provideTranslocoScope } from '@jsverse/transloco';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { ProjectViewDetailModule } from 'app/features/installations/project/components/project-view-detail/project-view-detail.module';
import { ProjectViewDetailActionComponent } from './project-view-detail-action.component';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [ProjectViewDetailActionComponent],
  exports: [ProjectViewDetailActionComponent],
  imports: [CommonModule, MatButtonModule, ProjectViewDetailModule, ReactiveFormsModule, TranslocoModule],
  providers: [provideTranslocoScope({ scope: 'installations/project', alias: 'installations.project' })],
  bootstrap: [],
})
export class ProjectViewDetailActionModule {}
