/* @autogenerated */
import { TranslocoService } from '@jsverse/transloco';
import { ActionContainerComponent } from 'app/common/toolkit/action/action-container.component';
import { Action } from 'app/common/toolkit/action/action.model';
import { Tick } from 'app/common/data/repository/repository.model';
import { ClientRepository } from 'app/features/organization/client/repository/client-repository.service';
import { Acl } from 'app/common/data/acl/acl.model';
import { Client } from 'app/features/organization/client/model/client.model';
import { Subscription } from 'rxjs';
import { MatSnackBar } from '@angular/material/snack-bar';
import { MatDialog, MatDialogRef } from '@angular/material/dialog';
import { LongTaskViewComponent } from 'app/common/toolkit/long-task-view/long-task-view.component';
import { OnDestroy, input, viewChild, Component, signal, TemplateRef } from '@angular/core';

@Component({
  selector: 'client-view-enable-selection-action',
  standalone: false,
  templateUrl: './client-view-enable-selection-action.component.html',
  styleUrl: './client-view-enable-selection-action.component.scss',
})
export class ClientViewEnableSelectionActionComponent implements Action, OnDestroy {
  readonly name = 'enableSelection';
  readonly contextual = true;
  readonly multiple = true;
  container = signal<ActionContainerComponent | undefined>(undefined);
  selection = signal<any[]>([]);
  render = signal<TemplateRef<any> | undefined>(undefined);
  dialogTemplate = viewChild<TemplateRef<any>>('dialogTemplate');

  title = signal<string>('Borrando el item');
  label = signal<string>('Delete');
  icon = signal<string>('visibility');
  tooltip = signal<string>('Borra el elemento seleccionado');
  default = input<boolean>(false);

  noMatchSignal = signal(false);
  visibleValue = signal(false);
  enabledValue = signal(true);

  acl: Tick<{ generic: Acl; specific: Acl }, string | null>;

  private dialgoRef?: MatDialogRef<any, any>;
  private dialogSubs?: Subscription;
  private dismiss = 'Close';
  private report = 'Deleted...';
  private progress = 'Deleted...';

  constructor(
    private readonly repository: ClientRepository,
    private readonly dialog: MatDialog,
    private readonly snakeBar: MatSnackBar,
    transloco: TranslocoService,
  ) {
    this.acl = repository.acl();
    this.acl.fetch(null).subscribe((info) => {
      this.visibleValue.set(this.allowed(info?.generic));
    });
    transloco.selectTranslateObject('action.enable-selection', {}, 'organization/client').subscribe((val) => {
      if (val.label) {
        this.label.set(val.label);
      }
      if (val.tooltip) {
        this.tooltip.set(val.tooltip);
      }
      if (val.icon) {
        this.icon.set(val.icon);
      }
      if (val.title) {
        this.title.set(val.title);
      }
      if (val.dismiss) {
        this.dismiss = val.dismiss;
      }
      if (val.report) {
        this.report = val.report;
      }
      if (val.progress) {
        this.progress = val.progress;
      }
    });
  }

  visible(items: any[]) {
    const canApply = items.every((item) => item.enabled !== true) && true;
    return canApply ? this.visibleValue : this.noMatchSignal;
  }

  enabled(items: any[]) {
    return this.enabledValue;
  }
  run(): void {
    const template = this.dialogTemplate();
    if (template) {
      this.dialgoRef?.close();
      this.dialgoRef = this.dialog.open(template);
      this.dialogSubs = this.dialgoRef.afterClosed().subscribe((val) => {
        if (val) {
          this.enableSelection(this.selection());
        } else {
          this.container()?.close();
        }
      });
    }
  }

  ngOnDestroy(): void {
    this.dialgoRef?.close();
    this.dialogSubs?.unsubscribe();
  }

  private enableSelection(items: Client[]) {
    const filter = { uids: items.map((item) => item.uid) };
    this.dialgoRef = this.dialog.open(LongTaskViewComponent, {
      data: {
        title: this.progress,
        progress: this.repository.enableSelection(filter),
      },
    });
    this.dialogSubs = this.dialgoRef.afterClosed().subscribe((val) => {
      this.container()?.selectionModel.clearSelection();
      this.container()?.close();
      this.snakeBar.open(this.report, this.dismiss, { duration: 5000 });
    });
  }
  private allowed(allow: Acl | undefined) {
    return this.repository.canDeleteSelection() && !!allow?.allows?.find((info) => info.name == 'enable')?.allowed;
  }
}
