/* @autogenerated */
import { TranslocoModule, provideTranslocoScope } from '@jsverse/transloco';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { FloorViewFormGroupModule } from 'app/features/organization/floor/components/floor-view-form-group/floor-view-form-group.module';
import { FloorViewCreateActionComponent } from './floor-view-create-action.component';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [FloorViewCreateActionComponent],
  exports: [FloorViewCreateActionComponent],
  imports: [CommonModule, FloorViewFormGroupModule, MatButtonModule, ReactiveFormsModule, TranslocoModule],
  providers: [provideTranslocoScope({ scope: 'organization/floor', alias: 'organization.floor' })],
  bootstrap: [],
})
export class FloorViewCreateActionModule {}
