/* @autogenerated */
import { ProjectViewStandarActionsModule } from 'app/features/installations/project/components/project-view-standar-actions/project-view-standar-actions.module';
import { ProjectViewListComponent } from './project-view-list.component';
import { CommonModule } from '@angular/common';
import { ListViewModule } from '@common/toolkit/list-view/list-view.module';
import { TranslocoModule, provideTranslocoScope } from '@jsverse/transloco';
import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';
import { MatExpansionModule } from '@angular/material/expansion';
import { ReactiveFormsModule } from '@angular/forms';
import { ProjectViewSearchModule } from '../project-view-search/project-view-search.module';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [ProjectViewListComponent],
  exports: [ProjectViewListComponent],
  imports: [
    CommonModule,
    ListViewModule,
    MatButtonModule,
    MatExpansionModule,
    MatIconModule,
    ProjectViewSearchModule,
    ProjectViewStandarActionsModule,
    ReactiveFormsModule,
    TranslocoModule,
  ],
  providers: [provideTranslocoScope({ scope: 'installations/project', alias: 'installations.project' })],
  bootstrap: [],
})
export class ProjectViewListModule {}
