/* @autogenerated */
import { Tick } from 'app/common/data/repository/repository.model';
import { Acl } from 'app/common/data/acl/acl.model';
import { Client } from 'app/features/organization/client/model/client.model';
import { ClientRepository } from 'app/features/organization/client/repository/client-repository.service';
import { SubFormEditable } from 'app/common/toolkit/editable/subform-editable';
import { BaseEditable } from 'app/common/toolkit/editable/base-editable';
import { Validators, FormGroup, FormControl } from '@angular/forms';
import { effect, computed, Component } from '@angular/core';

@Component({
  selector: 'client-view-form-group',
  templateUrl: './client-view-form-group.component.html',
  styleUrls: ['./client-view-form-group.component.scss'],
  providers: BaseEditable.getValidableAccessorProvider(ClientViewFormGroupComponent),
  standalone: false,
})
export class ClientViewFormGroupComponent extends SubFormEditable<Client> {
  acl: Tick<{ generic: Acl; specific: Acl }, string | null>;
  uid = computed(() => this.value()?.uid);
  public constructor(clientRepository: ClientRepository) {
    super(
      new FormGroup({
        uid: new FormControl<string>(''),
        name: new FormControl<string>('', [Validators.required]),
        enabled: new FormControl<boolean>(true),
        version: new FormControl<number>(0),
      }),
    );
    this.acl = clientRepository.acl();
    effect(() => {
      this.acl.fetch(this.uid() || null);
    });
    effect(() => {
      const vals = this.acl();
      const value = this.value();
      const on = this.uid() ? vals?.specific : vals?.generic;
      setTimeout(() => {
        this.definedFixed.set(on?.fields?.noEditables || []);
        this.definedHidden.set(on?.fields?.noVisibles || []);
      });
    });
    this.defaultValues = () => {
      return {
        uid: '',
        name: '',
        enabled: true,
        version: 0,
      };
    };
  }
}
