/* @autogenerated */
import { TranslocoModule, provideTranslocoScope } from '@jsverse/transloco';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { ProjectDeviceViewDetailModule } from 'app/features/installations/project-device/components/project-device-view-detail/project-device-view-detail.module';
import { ProjectDeviceViewDetailActionComponent } from './project-device-view-detail-action.component';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [ProjectDeviceViewDetailActionComponent],
  exports: [ProjectDeviceViewDetailActionComponent],
  imports: [CommonModule, MatButtonModule, ProjectDeviceViewDetailModule, ReactiveFormsModule, TranslocoModule],
  providers: [provideTranslocoScope({ scope: 'installations/project-device', alias: 'installations.project-device' })],
  bootstrap: [],
})
export class ProjectDeviceViewDetailActionModule {}
