/* @autogenerated */
import { ClientViewFormGroupModule } from 'app/features/organization/client/components/client-view-form-group/client-view-form-group.module';
import { ReactiveFormsModule } from '@angular/forms';
import { ClientViewDetailComponent } from './client-view-detail.component';
import { provideTranslocoScope } from '@jsverse/transloco';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [ClientViewDetailComponent],
  exports: [ClientViewDetailComponent],
  imports: [ClientViewFormGroupModule, ReactiveFormsModule],
  providers: [provideTranslocoScope({ scope: 'organization/client', alias: 'organization.client' })],
  bootstrap: [],
})
export class ClientViewDetailModule {}
