/* @autogenerated */
import { ProjectDevice } from '../model/project-device.model';
import { Observable, of } from 'rxjs';
export function appwriteDataNormalizer(data: ProjectDevice): Observable<ProjectDevice> {
  const copy = { ...data } as any;
  copy.project = (data as any)?.project?.$ref;
  copy.floor = (data as any)?.floor?.$ref;
  copy.type = (data as any)?.type?.$ref;
  copy.model = (data as any)?.model?.$ref;
  copy.configTemplate = (data as any)?.configTemplate?.$ref;
  return of(copy);
}
