/* @autogenerated */
import { QueryConstraint, where } from 'firebase/firestore';
import { ProjectDevice } from '../model/project-device.model';
import { Observable, of } from 'rxjs';
export function firebaseDataNormalizer(data: ProjectDevice): Observable<ProjectDevice> {
  return of(data);
}
