/* @autogenerated */
import { Floor } from '../model/floor.model';
import { Observable, of } from 'rxjs';
export function appwriteReader(data: any): Floor {
  const copy = { ...data } as any;
  copy.site = { $ref: data.site, $id: (data as any).site?.$id };
  return copy;
}
