/* @autogenerated */
import { Floor } from '../model/floor.model';
import { Observable, of } from 'rxjs';
export function appwriteDataNormalizer(data: Floor): Observable<Floor> {
  const copy = { ...data } as any;
  copy.site = (data as any)?.site?.$ref;
  return of(copy);
}
