/* @autogenerated */
import { FloorFilter } from '../model/floor.model';
import { Observable, of } from 'rxjs';
export function appwriteQuery(query: FloorFilter): Observable<string[]> {
  const constraints: string[] = [];
  return of(constraints);
}
