/* @autogenerated */
import { QueryConstraint, where } from 'firebase/firestore';
import { FloorFilter } from '../model/floor.model';
import { Observable, of } from 'rxjs';
export function firebaseQuery(query: FloorFilter): Observable<QueryConstraint[]> {
  const constraints: QueryConstraint[] = [];
  return of(constraints);
}
