/* @autogenerated */
import { appwriteQuery } from './appwrite-query.method';
import { appwriteAcl } from './appwrite-acl.method';
import { selectorProvider, SelectorProvider } from '@common/data/selector-provider';
import { Acl } from '@common/data/acl/acl.model';
import { RepositoryMetadata, RepositoryService } from '@common/data/repository/repository.service';
import { appwriteReader } from './appwrite-reader.method';
import { appwriteDataNormalizer } from './appwrite-data-normalizer.method';
import { SiteRepository } from '@features/organization/site/repository/site-repository.service';
import { Slide, DownloadBlob, UploadProgress } from '@common/data/repository/provider/repository-provider.interface';
import { AppwriteDataBuilder } from '@common/appwrite/data/appwrite-data-builder.service';
import { Floor, FloorFilter, FloorProjection } from '@features/organization/floor/model/floor.model';
import { Observable, of } from 'rxjs';
import { Shift, Tick } from '@common/data/repository/repository.model';
import { Injectable, Signal } from '@angular/core';

@Injectable({ providedIn: 'root' })
export class FloorRepository {
  private readonly repo: RepositoryService<Floor, FloorFilter>;
  public static metadata(api: AppwriteDataBuilder): RepositoryMetadata<Floor, FloorFilter> {
    return {
      key: 'uid',
      name: 'floor',
      provider: api.provider(
        'uid',
        'netconfighub_documents',
        'netconfighub_floor',
        'netconfighub_attacheds',
        appwriteAcl,
        appwriteQuery,
        appwriteReader,
        appwriteDataNormalizer,
      ),
      reference: (name: string): RepositoryService<any, any> | null => {
        if ('site' == name) {
          return new RepositoryService(SiteRepository.metadata(api));
        }
        return null;
      },
    };
  }
  constructor(api: AppwriteDataBuilder) {
    this.repo = new RepositoryService(FloorRepository.metadata(api));
  }
  acl(): Tick<{ generic: Acl; specific: Acl }, string | null> {
    return this.repo.acl();
  }
  checkAcl(key?: string): Observable<Acl> {
    return this.repo.checkAcl(key || null);
  }
  generateComb(): string {
    return this.repo.generateComb();
  }

  add(item: Floor): Observable<Floor> {
    item['uid'] = this.generateComb();
    return this.repo.add(item);
  }
  update(item: Floor): Observable<Floor> {
    return this.repo.update(item);
  }
  deleteByKey(item: string): Observable<void> {
    return this.repo.deleteByKey(item);
  }
  canDeleteSelection(): boolean {
    return this.repo.canDeleteSelection();
  }
  deleteSelection(filter: FloorFilter): Observable<any> {
    return this.repo.deleteSelection(this.publicQueryFilter(filter));
  }
  retrieve(code: string): Observable<Floor | undefined> {
    return this.repo.retrieve(code);
  }
  projection(includes: string[]): Tick<FloorProjection, string> {
    return this.repo.projection(includes);
  }
  list(filter: FloorFilter): Observable<Slide<Floor>> {
    return this.repo.list(this.publicQueryFilter(filter));
  }
  values(filter: FloorFilter): Observable<Floor[]> {
    return this.repo.values(this.publicQueryFilter(filter));
  }
  projections(includes: string[]): Shift<FloorProjection[], FloorFilter> {
    return this.repo.projections(includes);
  }
  downloadImagePath(url?: string): Observable<DownloadBlob> | null {
    return url ? this.repo.downloadFile(url) : null;
  }
  storeImagePath(file: File): Observable<UploadProgress> {
    return this.repo.storeFile('/-/temp-image-path', 'file', file);
  }
  selectorProvider(filter?: Signal<FloorFilter>): SelectorProvider<Floor, { $ref: string }> {
    return selectorProvider({
      search: (text: string) => {
        const filterValue = filter ? filter() : { limit: 10 };
        filterValue.search = text;
        return this.values(filterValue);
      },
      display: (item: Floor) => {
        return item.name!;
      },
      value: (item: Floor) => {
        return { $ref: item.uid!, $id: (item as any).$id };
      },
      select: (ref: { $ref: string }) => {
        return ref['$ref'] ? this.retrieve(ref['$ref']) : of(undefined);
      },
      equals: (one: { $ref: string }, other: { $ref: string }) => {
        return one.$ref === other.$ref;
      },
    });
  }
  private publicQueryFilter(filter: FloorFilter): FloorFilter {
    const morphed = {} as any;
    if (filter.search) {
      morphed['search'] = filter.search;
    }
    if (filter.uids) {
      morphed['uids'] = filter.uids.join(',');
    }
    if (filter.limit) {
      morphed['limit'] = filter.limit;
    }
    if (filter.order) {
      morphed['order'] = filter.order;
    }
    if (filter.name) {
      morphed['name'] = filter.name;
    }
    if (filter.site) {
      morphed['site'] = filter.site;
    }
    if (filter.sites) {
      morphed['sites'] = filter.sites;
    }
    return morphed;
  }
}
