/* @autogenerated */
import { FormControl } from '@angular/forms';
import { DeviceInstance } from 'app/features/installations/device-instance/model/device-instance.model';
import { input, effect, Component } from '@angular/core';

@Component({
  selector: 'device-instance-view-detail',
  templateUrl: './device-instance-view-detail.component.html',
  styleUrl: './device-instance-view-detail.component.scss',
  standalone: false,
})
export class DeviceInstanceViewDetailComponent {
  data = input.required<DeviceInstance | null>();
  form = new FormControl<DeviceInstance | undefined>({ value: undefined, disabled: true });

  public constructor() {
    effect(() => this.form.patchValue(this.data()));
  }
}
