/* @autogenerated */
import { CommonModule } from '@angular/common';
import { Component, input } from '@angular/core';
import { ReactiveFormsModule } from '@angular/forms';
import { TranslocoModule } from '@jsverse/transloco';
import { BaseEditable } from '../base-editable';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatSelectModule } from '@angular/material/select';
import { MatInputModule } from '@angular/material/input';

@Component({
  template: `
    <mat-form-field>
      <mat-label>{{ label() + '.label' | transloco }}</mat-label>
      <mat-select
        [required]="required()"
        placeholder="{{ label() + '.placeholder' | transloco }}"
        [formControl]="control"
      >
        @for (op of options(); track $index) {
          <mat-option [value]="op">{{ label() + '.options.' + (!!op ? op : 'null') | transloco }}</mat-option>
        }
      </mat-select>
      @for (error of errorMessages(); track $index) {
        <mat-error>
          {{ label() + '.error.' + error | transloco }}
        </mat-error>
      }
    </mat-form-field>
  `,
  selector: 'editable-choose',
  imports: [ReactiveFormsModule, MatFormFieldModule, MatSelectModule, MatInputModule, CommonModule, TranslocoModule],
  providers: BaseEditable.getAccessorProvider(EditableChooseComponent),
  standalone: true,
})
export class EditableChooseComponent extends BaseEditable<string> {
  options = input.required<string[]>();
}
