/* @autogenerated */
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { LocalRouteDirective } from './local-route.directive';
import { LocalRouteContextComponent } from './local-route-context.component';

@NgModule({
  declarations: [LocalRouteDirective, LocalRouteContextComponent],
  exports: [LocalRouteDirective, LocalRouteContextComponent],
  imports: [CommonModule],
})
export class LocalRouteModule {}
