/* @autogenerated */
import { TranslocoModule, provideTranslocoScope } from '@jsverse/transloco';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { DeviceCheckViewDetailModule } from 'app/features/installations/device-check/components/device-check-view-detail/device-check-view-detail.module';
import { DeviceCheckViewDetailActionComponent } from './device-check-view-detail-action.component';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [DeviceCheckViewDetailActionComponent],
  exports: [DeviceCheckViewDetailActionComponent],
  imports: [CommonModule, DeviceCheckViewDetailModule, MatButtonModule, ReactiveFormsModule, TranslocoModule],
  providers: [provideTranslocoScope({ scope: 'installations/device-check', alias: 'installations.device-check' })],
  bootstrap: [],
})
export class DeviceCheckViewDetailActionModule {}
