/* @autogenerated */
import { ClientViewStandarActionsModule } from 'app/features/organization/client/components/client-view-standar-actions/client-view-standar-actions.module';
import { ClientViewListComponent } from './client-view-list.component';
import { CommonModule } from '@angular/common';
import { ListViewModule } from '@common/toolkit/list-view/list-view.module';
import { TranslocoModule, provideTranslocoScope } from '@jsverse/transloco';
import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';
import { MatExpansionModule } from '@angular/material/expansion';
import { ReactiveFormsModule } from '@angular/forms';
import { ClientViewSearchModule } from '../client-view-search/client-view-search.module';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [ClientViewListComponent],
  exports: [ClientViewListComponent],
  imports: [
    ClientViewSearchModule,
    ClientViewStandarActionsModule,
    CommonModule,
    ListViewModule,
    MatButtonModule,
    MatExpansionModule,
    MatIconModule,
    ReactiveFormsModule,
    TranslocoModule,
  ],
  providers: [provideTranslocoScope({ scope: 'organization/client', alias: 'organization.client' })],
  bootstrap: [],
})
export class ClientViewListModule {}
