/* @autogenerated */
import { ClientRepository } from 'app/features/organization/client/repository/client-repository.service';
import { ClientFilter, ClientProjection } from 'app/features/organization/client/model/client.model';
import { FormControl } from '@angular/forms';
import { Shift } from '@common/data/repository/repository.model';
import { input, effect, Component } from '@angular/core';

@Component({
  selector: 'client-view-list',
  templateUrl: './client-view-list.component.html',
  styleUrls: ['./client-view-list.component.scss'],
  standalone: false,
})
export class ClientViewListComponent {
  filters = input<ClientFilter>();
  actionName = input<string>('client');
  fixed = input<{ [key: string]: any }>();
  hidden = input<{ [key: string]: any }>();
  search = new FormControl<any>(undefined);
  list: Shift<ClientProjection[], ClientFilter>;

  constructor(repository: ClientRepository) {
    this.list = repository.projections([]);
    effect(() => {
      setTimeout(() => this.makeSearch());
    });
  }
  makeSearch() {
    const result = { limit: 10 } as any;
    const filter = this.search.value;
    const external = this.filters();
    if (external?.search) {
      result.search = external.search;
    }
    if (external?.name) {
      result.name = external.name;
    }
    if (filter?.search) {
      result.search = filter.search;
    }
    if (filter?.name) {
      result.name = filter.name;
    }
    if (filter?.order) {
      result.order = filter.order;
    }
    this.list.fetch(result);
  }

  next() {
    this.list.next();
  }

  reload() {
    this.list.reset();
  }

  prev() {
    console.log('PREV');
  }
}
